<ips:template parameters="$nextStep, $orientation='vertical'" />

<div class='ipsSpacer_bottom ipsPad_half' data-role='profileWidget' data-controller="core.front.core.profileCompletion">
	{{if $orientation == 'horizontal'}}
		<span class='ipsPos_right'><a class='ipsButton ipsButton_primary' href='{url="app=core&module=system&controller=settings&do=completion}'>{lang="complete_my_profile"}</a> {lang="or"} <a class='ipsButton ipsButton_link' href='{url="app=core&module=system&controller=settings&do=dismissProfile" csrf="true"}' data-role='dismissProfile'>{lang="dismiss"}</a></span>
	{{endif}}
	<div class='ipsType_richText'>{lang="profile_step_text_{$nextStep->id}"}</div>
	<span class="ipsAttachment_progress"><span style='width: {expression="\IPS\Member::loggedIn()->profileCompletionPercentage()"}%'></span></span><br>
	<span class='ipsType_light'>{lang="profile_completion_percent" sprintf="\IPS\Member::loggedIn()->profileCompletionPercentage() . '%'"}</span>
	{{if $orientation == 'vertical'}}
		<br>
		<a class='ipsButton ipsButton_primary' href='{url="app=core&module=system&controller=settings&do=completion}'>{lang="complete_my_profile"}</a> {lang="or"} <a class='ipsButton ipsButton_link' href='{url="app=core&module=system&controller=settings&do=dismissProfile" csrf="true"}' data-role='dismissProfile'>{lang="dismiss"}</a>
	{{endif}}
</div>