<ips:template parameters="$advertisement, $acpLink=NULL" />
{{if count( $advertisement->_images )}}
<div class='ipsAdvertisement ipsSpacer_both ipsSpacer_half'>
	<ul class='ipsList_inline ipsType_center ipsList_reset ipsList_noSpacing'>
		<li class='ipsAdvertisement_large ipsResponsive_showDesktop ipsResponsive_inlineBlock ipsAreaBackground_light'>
			{{if $advertisement->link}}
				<a href='{{if $acpLink}}{$acpLink->makeSafeForAcp()}{{else}}{url="app=core&module=system&controller=redirect&do=advertisement&ad=$advertisement->id" base="front" csrf="true"}{{endif}}' {{if $advertisement->new_window}}target='_blank'{{endif}} rel='nofollow noopener'>
			{{endif}}
				<img src='{file="$advertisement->_images['large']" extension="$advertisement->storageExtension()"}' alt="{lang="advertisement_alt"}" class='ipsImage ipsContained'>
			{{if $advertisement->link}}
				</a>
			{{endif}}
		</li>
		{{if !$acpLink }}
		<li class='ipsAdvertisement_medium ipsResponsive_showTablet ipsResponsive_inlineBlock ipsAreaBackground_light'>
			{{if $advertisement->link}}
				<a href='{{if $acpLink}}{$acpLink->makeSafeForAcp()}{{else}}{url="app=core&module=system&controller=redirect&do=advertisement&ad=$advertisement->id" base="front" csrf="true"}{{endif}}' {{if $advertisement->new_window}}target='_blank'{{endif}} rel='nofollow noopener'>
			{{endif}}
				<img src='{{if !empty( $advertisement->_images['medium'] )}}{file="$advertisement->_images['medium']" extension="$advertisement->storageExtension()"}{{else}}{file="$advertisement->_images['large']" extension="$advertisement->storageExtension()"}{{endif}}' alt="{lang="advertisement_alt"}" class='ipsImage ipsContained'>
			{{if $advertisement->link}}
				</a>
			{{endif}}
		</li>

		<li class='ipsAdvertisement_small ipsResponsive_showPhone ipsResponsive_inlineBlock ipsAreaBackground_light'>
			{{if $advertisement->link}}
				<a href='{{if $acpLink}}{$acpLink->makeSafeForAcp()}{{else}}{url="app=core&module=system&controller=redirect&do=advertisement&ad=$advertisement->id" base="front" csrf="true"}{{endif}}' {{if $advertisement->new_window}}target='_blank'{{endif}} rel='nofollow noopener'>
			{{endif}}
				<img src='{{if !empty( $advertisement->_images['small'] )}}{file="$advertisement->_images['small']" extension="$advertisement->storageExtension()"}{{elseif !empty( $advertisement->_images['medium'] )}}{file="$advertisement->_images['medium']" extension="$advertisement->storageExtension()"}{{else}}{file="$advertisement->_images['large']" extension="$advertisement->storageExtension()"}{{endif}}' alt="{lang="advertisement_alt"}" class='ipsImage ipsContained'>
			{{if $advertisement->link}}
				</a>
			{{endif}}
		</li>
		{{endif}}
	</ul>
	{{if $acpLink}}
		<div class="ipsType_center ipsType_small"><a href="{$acpLink->makeSafeForAcp()}">{$acpLink}</a></div>
	{{endif}}
</div>
{{endif}}