<ips:template parameters="$url, $client, $scopes, $login, $error" />
<div data-controller="core.global.core.framebust" class="ipsSpacer_top ipsSpacer_double">
	<div class="ipsType_center ipsSpacer_bottom ipsPad">
		<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="oauth_authorize_title" sprintf="\IPS\Settings::i()->board_name"}</h1>
		{{if \IPS\Login::registrationType() != 'disabled'}}
			<p class='ipsType_reset ipsType_large ipsType_center ipsType_light'>
				{lang="dont_have_an_account"}
				{{if \IPS\Login::registrationType() == 'redirect'}}
					<a href='{expression="\IPS\Settings::i()->allow_reg_target"}' target="_blank">
				{{else}}
					<a href='{expression="\IPS\Http\Url::internal( 'app=core&module=system&controller=register', 'front', 'register' )->setQueryString( 'ref', base64_encode( $url ) )"}' {{if \IPS\Login::registrationType() == 'normal'}}data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="sign_up"}'{{endif}}>
				{{endif}}
				{lang="sign_up"}</a>
			</p>
		{{endif}}
	</div>
	<form accept-charset='utf-8' method='post' action='{$login->url}' data-controller="core.global.core.login">
		<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
		{{$usernamePasswordMethods = $login->usernamePasswordMethods();}}
		{{$buttonMethods = $login->buttonMethods();}}
		{{if $usernamePasswordMethods and $buttonMethods}}
			{{if $error}}
				<div class="ipsMessage ipsMessage_error">{lang="$error"}</div>
			{{endif}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
				<div class='ipsColumn ipsColumn_fluid'>
					<div class='{{if !request.isAjax()}}ipsBox{{endif}} ipsPad'>
						{template="loginForm" app="core" group="system" params="$login"}
					</div>
				</div>
				<div class='ipsColumn ipsColumn_veryWide'>
					<div class='{{if !request.isAjax()}}ipsBox{{endif}} ipsPad'>
						<h2 class='ipsType_sectionHead'>{lang="sign_in_faster"}</h2>
						{{if count( $buttonMethods ) > 1}}
							<p class='ipsType_normal ipsType_reset ipsType_light'>{lang='sign_in_with_these'}</p>
						{{endif}}
						{{foreach $buttonMethods as $method}}
							<div class='ipsPad_half ipsType_center'>
								{$method->button()|raw}
							</div>
						{{endforeach}}
					</div>
				</div>
			</div>
		{{elseif $usernamePasswordMethods}}
			<div class='cLogin_single ipsPos_center'>
			{{if $error}}
				<p class="ipsMessage ipsMessage_error">{lang="$error"}</p>
			{{endif}}
				<div class="{{if !request.isAjax()}}ipsBox{{endif}} ipsPad">
					{template="loginForm" app="core" group="system" params="$login"}
				</div>
			</div>
		{{elseif $buttonMethods}}
			<div class="cLogin_single ipsPos_center">
				{{if $error}}
					<p class="ipsMessage ipsMessage_error">{lang="$error"}</p>
				{{endif}}
				{{foreach $buttonMethods as $method}}
					<div class='ipsPad_half ipsType_center'>
						{$method->button()|raw}
					</div>
				{{endforeach}}
			</div>
		{{endif}}
	</form>
</div>