<ips:template parameters="$row, $apiKey, $client, $member" />
{{if $row['api_key']}}
	{{if $apiKey}}
		<i class="fa fa-key" title="{lang="api_id"}" data-ipsTooltip></i> {$apiKey->_title}
	{{else}}
		<i class="fa fa-key" title="{lang="api_id"}" data-ipsTooltip></i> <code>{$row['api_key']}</code>
	{{endif}}
{{elseif $row['access_token']}}
	{{if $row['member_id'] and $member}}
		{template="userPhoto" group="global" params="$member, 'tiny'"}
		{{if $member->member_id}}
			{template="userLink" group="global" params="$member, 'tiny'"}
		{{else}}
			{lang="deleted_member"}
		{{endif}}
		{lang="api_log_member_client" sprintf="$client->_title"}
	{{elseif $client}}
		<i class="fa fa-cubes" title="{lang="oauth_client"}" data-ipsTooltip></i> {$client->_title}
	{{else}}
		<i class="fa fa-cubes" title="{lang="oauth_client"}" data-ipsTooltip></i> <code>{$row['access_token']}</code>
	{{endif}}
{{else}}
	<em class="ipsType_light">{lang="none"}</em>
{{endif}}