<ips:template parameters="" />

<div data-embedInfo-maxSize='500' class='ipsRichEmbed'>
	<div class='ipsType_center ipsType_light ipsPad'>
		<i class='fa fa-frown-o ipsType_veryLarge ipsType_light'></i>
		<p class='ipsType_reset ipsType_normal ipsPad'>
			{{if \IPS\Member::loggedIn()->member_id}}
				{lang="embed_no_perm_desc"}
			{{else}}
				{lang="embed_no_perm_desc_log_in"}
			{{endif}}
		</p>
	</div>
</div>