<ips:template parameters="" />

{{if $announcements = \IPS\core\Announcements\Announcement::loadAllByLocation('top')}}
<div class='cAnnouncements' data-controller="core.front.core.announcementBanner" >
	{{foreach $announcements as $announcement}}
	{{if !isset( \IPS\Request::i()->cookie['announcement_' . $announcement->id ] )}}
	<div class='cAnnouncementPageTop ipsMessage ipsMessage_{$announcement->color}' data-announcementId="{$announcement->id}">
		{$announcement->title} <a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{lang="read_more"}</a>
		<a href='#' data-role="dismissAnnouncement">×</a>
	</div>
	{{endif}}
	{{endforeach}}
</div>
{{endif}}