<ips:template parameters="" />
{{if theme.body_fontcustom || theme.nav_fontcustom}}
  <script>WebFontConfig = {google: {families: [{{if theme.body_fontcustom}}'{theme="body_fontcustom"}:400,600', {{endif}}{{if theme.nav_fontcustom}}'{theme="nav_fontcustom"}:400,600'{{endif}}]} }; !function(e){var t=e.createElement("script"),o=e.scripts[0];t.src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js",o.parentNode.insertBefore(t,o)}(document);</script>
{{endif}}
{{if theme.specific_cat_style == 1}}
<style type="text/css">
{{if theme.category_r1 == '1'}}
	{{if theme.cat_id_r1}}
		{{foreach explode(',', theme.cat_id_r1) as $id}}
			.cForumList [data-categoryid="{$id}"] h2{
				background-color: {theme="cat_ti_bg_r1"};
				{{if theme.cat_ti_bg_gradi_r1}}{theme="cat_ti_bg_gradi_r1"}{{endif}}
			}
			.cForumList [data-categoryid="{$id}"] a.ipsType_sectionTitle,
			.cForumList [data-categoryid="{$id}"] .ipsType_sectionTitle a{
				color: {theme="cat_ti_font_r1"};
			}
			{{if theme.cat_private_r1 == '1'}}
				{{if theme.cat_private_g_r1 == '*' || \IPS\Member::loggedIn()->inGroup( explode( ',', theme.cat_private_g_r1 ) )}}{{else}}
					.cForumList [data-categoryid="{$id}"] > ol:before {
    					content: "";
    					position: absolute;
    					top: 0;
    					width: 100%;
    					height: 100%;
    					z-index: 1;
					}
					.cForumList [data-categoryid="{$id}"] > ol:before {
						background-color: {hextorgb="cat_private_bg_r1" opacity="0.70"};
					}
					.cForumList [data-categoryid="{$id}"] > ol:after {
  						content: "{theme="cat_private_ti_r1"}";
						font-size: 25px;
						color: {theme="cat_private_ti_font_r1"};
						position: absolute;
						top: 50%;
						left: 50%;
						width: 100%;
						text-align: center;
						-ms-transform: translate(-50%, -50%);
						-webkit-transform: translate(-50%, -50%);
						transform: translate(-50%, -50%);
						z-index: 1;
					}
				{{endif}}
			{{endif}}
		{{endforeach}}
	{{endif}}
{{endif}}
{{if theme.category_r2 == '1'}}
	{{if theme.cat_id_r2}}
		{{foreach explode(',', theme.cat_id_r2) as $id}}
			.cForumList [data-categoryid="{$id}"] h2{
				background-color: {theme="cat_ti_bg_r2"};
				{{if theme.cat_ti_bg_gradi_r2}}{theme="cat_ti_bg_gradi_r2"}{{endif}}
			}
			.cForumList [data-categoryid="{$id}"] a.ipsType_sectionTitle,
			.cForumList [data-categoryid="{$id}"] .ipsType_sectionTitle a{
				color: {theme="cat_ti_font_r2"};
			}
			{{if theme.cat_private_r2 == '1'}}
				{{if theme.cat_private_g_r2 == '*' || \IPS\Member::loggedIn()->inGroup( explode( ',', theme.cat_private_g_r2 ) )}}{{else}}
					.cForumList [data-categoryid="{$id}"] > ol:before {
    					content: "";
    					position: absolute;
    					top: 0;
    					width: 100%;
    					height: 100%;
    					z-index: 1;
					}
					.cForumList [data-categoryid="{$id}"] > ol:before {
						background-color: {hextorgb="cat_private_bg_r2" opacity="0.70"};
					}
					.cForumList [data-categoryid="{$id}"] > ol:after {
  						content: "{theme="cat_private_ti_r2"}";
						font-size: 25px;
						color: {theme="cat_private_ti_font_r2"};
						position: absolute;
						top: 50%;
						left: 50%;
						width: 100%;
						text-align: center;
						-ms-transform: translate(-50%, -50%);
						-webkit-transform: translate(-50%, -50%);
						transform: translate(-50%, -50%);
						z-index: 1;
					}
				{{endif}}
			{{endif}}
		{{endforeach}}
	{{endif}}
{{endif}}
{{if theme.category_r3 == '1'}}
	{{if theme.cat_id_r3}}
		{{foreach explode(',', theme.cat_id_r3) as $id}}
			.cForumList [data-categoryid="{$id}"] h2{
				background-color: {theme="cat_ti_bg_r3"};
				{{if theme.cat_ti_bg_gradi_r3}}{theme="cat_ti_bg_gradi_r3"}{{endif}}
			}
			.cForumList [data-categoryid="{$id}"] a.ipsType_sectionTitle,
			.cForumList [data-categoryid="{$id}"] .ipsType_sectionTitle a{
				color: {theme="cat_ti_font_r3"};
			}
			{{if theme.cat_private_r3 == '1'}}
				{{if theme.cat_private_g_r3 == '*' || \IPS\Member::loggedIn()->inGroup( explode( ',', theme.cat_private_g_r3 ) )}}{{else}}
					.cForumList [data-categoryid="{$id}"] > ol:before {
    					content: "";
    					position: absolute;
    					top: 0;
    					width: 100%;
    					height: 100%;
    					z-index: 1;
					}
					.cForumList [data-categoryid="{$id}"] > ol:before {
						background-color: {hextorgb="cat_private_bg_r3" opacity="0.70"};
					}
					.cForumList [data-categoryid="{$id}"] > ol:after {
  						content: "{theme="cat_private_ti_r3"}";
						font-size: 25px;
						color: {theme="cat_private_ti_font_r3"};
						position: absolute;
						top: 50%;
						left: 50%;
						width: 100%;
						text-align: center;
						-ms-transform: translate(-50%, -50%);
						-webkit-transform: translate(-50%, -50%);
						transform: translate(-50%, -50%);
						z-index: 1;
					}
				{{endif}}
			{{endif}}
		{{endforeach}}
	{{endif}}
{{endif}}
</style>
{{endif}}