<ips:template parameters="$handlers" />

<h2 class="ipsType_sectionHead">{lang="mfa_settings_title"}</h2>
<hr class='ipsHr'>
<p class='ipsType_normal ipsSpacer_bottom ipsSpacer_double'>{lang="mfa_ucp_blurb"}</p>

{{foreach $handlers as $key => $handler}}
	<div class="ipsSpacer_bottom ipsPad ipsAreaBackground_light ipsClearfix">
		<h2 class="ipsType_sectionHead ipsType_large">{$handler->ucpTitle()} {{if $handler->memberHasConfiguredHandler( \IPS\Member::loggedIn() )}}&nbsp;&nbsp;<span class='ipsType_positive ipsType_medium'><i class='fa fa-check'></i> {lang="enabled"}</span>{{endif}}</h2>
		<p class='ipsType_medium'>{$handler->ucpDesc()}</p>
		<ul class="ipsList_inline">
		{{if $handler->memberHasConfiguredHandler( \IPS\Member::loggedIn() )}}
			<li><a href="{url="app=core&module=system&controller=settings&area=mfa&do=enableMfa&type={$key}&_new=1" seoTemplate="settings_mfa" csrf="true"}" class="ipsButton ipsButton_verySmall ipsButton_primary">{lang="mfa_{$key}_reauth"}</a></li>
			<li>{lang="or"}</li>
			<li><a href="{url="app=core&module=system&controller=settings&area=mfa&do=disableMfa&type={$key}" seoTemplate="settings_mfa" csrf="true"}" class="ipsType_negative" data-confirm>{lang="mfa_disable"}</a></li>
		{{else}}
			<li><a href="{url="app=core&module=system&controller=settings&area=mfa&do=enableMfa&type={$key}&_new=1" seoTemplate="settings_mfa" csrf="true"}" class="ipsButton ipsButton_verySmall ipsButton_primary">{lang="enable"}</a></li>
		{{endif}}
		</ul>
	</div>
{{endforeach}}