<ips:template parameters="$theme, $templateNames, $template, $current" />

<form accept-charset='utf-8' action="{url="app=core&module=customization&controller=themes&do=saveTemplate&id={$theme->_id}"}" method="POST" id="editorForm">
	<input type="hidden" name="t_type" value="{$current['type']}">
	<input type="hidden" name="t_key" value="{{if $current['type'] == 'templates'}}{$template['TemplateKey']}{{else}}{$template['CssKey']}{{endif}}">
	<input type="hidden" name="t_app" value="{$current['app']}">
	<input type="hidden" name="t_location" value="{$current['location']}">
	<input type="hidden" name="t_group" value="{$current['group']}">
	<input type="hidden" name="t_name" value="{$current['template']}">
	<input type="hidden" name="t_item_id" value="{$current['item_id']}">
	
	<div id='elTemplateEditor' data-controller='core.admin.templates.main' data-normalURL="{url="app=core&module=customization&controller=themes&id={$theme->_id}"}" data-ajaxURL="{url="app=core&module=customization&controller=ajax&id={$theme->_id}"}">
		<div class='ipsColumns'>
			<div class='ipsColumn ipsColumn_wide' data-role="fileList" data-controller='core.admin.templates.fileList'>
				<div class='cTemplateControls' id='elTemplateEditor_fileListControls'>
					<div class="ipsClearfix" class="ipsJS_show">
						<input type='text' data-role="templateSearch" placeholder="{lang="search_templates"}" class="ipsPos_left">
						<a href='#elTemplateFilterMenu_menu' id='elTemplateFilterMenu' class='ipsButton ipsButton_light ipsButton_narrow ipsButton_small ipsPos_right' data-ipsMenu data-ipsMenu-selectable><i class="fa fa-filter"></i> &nbsp;<i class='fa fa-caret-down'></i></a>
					</div>
					<ul id='elTemplateFilterMenu_menu' role='menu' class='ipsMenu ipsMenu_selectable ipsMenu_auto ipsMenu_withStem ipsHide'>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='outofdate'><a href='#'>{lang="theme_template_outofdate"}</a></li>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='modified'><a href='#'>{lang="theme_template_modified"}</a></li>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='inherited'><a href='#'>{lang="theme_template_inherited"}</a></li>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='unique'><a href='#'>{lang="theme_template_unique"}</a></li>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='unmodified'><a href='#'>{lang="theme_template_unmodified"}</a></li>
					</ul>
					<ul id='elTemplateEditor_newItemMenu_menu' role='menu' class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide'>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=core&module=customization&controller=themes&do=cssForm&id={$theme->_id}"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="theme_template_add_css"}'>{lang="theme_template_new_css"}</a></li>
						<li class='ipsMenu_item'><a  role='menuitem' href='{url="app=core&module=customization&controller=themes&do=templateForm&id={$theme->_id}"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="theme_template_add_html"}'>{lang="theme_template_new_html"}</a></li>
					</ul>
				</div>
				<div class='ipsAreaBackground_reset'>
					<div class='ipsTabs ipsTabs_stretch ipsClearfix acpFormTabBar' id='elTemplateEditor_typeTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elTemplateEditor_fileList' data-ipsTabBar-updateURL='false'>
						<ul role="tablist">
							<li><a href='{url="app=core&module=customization&controller=themes&do=templates&id={$theme->_id}&t_type={$current['type']}&t_type=templates"}' class='ipsTabs_item ipsType_center {{if $current['type'] == 'templates'}}ipsTabs_activeItem{{endif}}' data-tabURL='{url="app=core&module=customization&controller=ajax&id={$theme->_id}&do=loadMenu&t_type=templates"}' data-type='templates'>{lang="theme_templates"}</a></li>
							<li><a href='{url="app=core&module=customization&controller=themes&do=templates&id={$theme->_id}&t_type={$current['type']}&t_type=css"}' class='ipsTabs_item ipsType_center {{if $current['type'] == 'css'}}ipsTabs_activeItem{{endif}}' data-tabURL='{url="app=core&module=customization&controller=ajax&id={$theme->_id}&do=loadMenu&t_type=css"}' data-type='css'>{lang="theme_css"}</a></li>
						</ul>
					</div>
					<section id='elTemplateEditor_fileList'>
						{template="templateEditorMenu" params="$theme, $templateNames, $current" app="core" location="admin" group="customization"}
					</section>
				</div>
				<div class='ipsAreaBackground_light ipsPad' id='elTemplateEditor_newButton'>
					<a href='#elTemplateEditor_newItemMenu_menu' id='elTemplateEditor_newItemMenu' class='ipsButton ipsButton_normal ipsButton_small ipsButton_fullWidth' data-ipsMenu data-ipsMenu-above>{lang="theme_template_new"} &nbsp;<i class='fa fa-caret-down'></i></a></li>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_fluid'  data-controller='core.admin.templates.fileEditor'>
				<div class='cTemplateControls'>
					<ul class='ipsList_inline ipsClearfix' id='elTemplateEditor_panelToolbar'>
						<li class='ipsPos_right'>
							<a href='#elTemplateEditor_preferences_menu' id='elTemplateEditor_preferences' class='ipsButton ipsButton_veryLight ipsButton_small' data-ipsMenu data-ipsMenu-selectable><i class='fa fa-cog'></i> <i class='fa fa-caret-down'></i></a>
							<ul id='elTemplateEditor_preferences_menu' class='ipsMenu ipsMenu_selectable ipsMenu_auto ipsMenu_withStem ipsHide'>
								<li class='ipsMenu_item' data-ipsMenuValue='wrap'><a href='#'>{lang="theme_wrap"}</a></li>
								<li class='ipsMenu_item' data-ipsMenuValue='lines'><a href='#'>{lang="theme_show_line"}</a></li>
								<li class='ipsMenu_item' data-ipsMenuValue='diff'><a href='#'>{lang="theme_show_original"}</a></li>
							</ul>
						</li>
						<li class='ipsPos_right {{if $current['type'] == 'css'}}ipsHide{{endif}}'>
							<a href='#' id='elTemplateEditor_variables' class='ipsButton ipsButton_veryLight ipsButton_small' data-ipsDialog data-ipsDialog-title='{lang="theme_edit_variables"}' data-ipsDialog-content="#elTemplateEditor_variablesDialog" data-ipsDialog-size='narrow'>{lang="theme_variables"}</a>
						</li>
						<li class='ipsPos_right {{if $current['type'] == 'templates'}}ipsHide{{endif}}'>
							<a href='#' id='elTemplateEditor_attributes' class='ipsButton ipsButton_veryLight ipsButton_small' data-ipsDialog data-ipsDialog-title='{lang="theme_edit_css"}' data-ipsDialog-content="#elTemplateEditor_attributesDialog" data-ipsDialog-size='narrow'>{lang="theme_attributes"}</a>
						</li>
						<li class='ipsPos_right'>
							<a href='{url="app=core&module=customization&controller=themes&do=deleteTemplate&t_type={$current['type']}&id={$theme->_id}&t_item_id={$current['item_id']}"}' class='ipsButton ipsButton_veryLight ipsButton_small {{if $template['InheritedValue'] == 'original'}}ipsButton_disabled{{endif}}' data-action="revert">{{if $template['InheritedValue'] == 'custom'}}{lang="delete"}{{else}}{lang="revert"}{{endif}}</a>
						</li>
						<li>
							<button type='submit' class='ipsButton ipsButton_primary ipsButton_small' data-action="save">{lang="save"}</button>
						</li>					
						<li>
							<span data-role='loading' class='ipsHide'><i class='icon-spinner2 ipsLoading_tinyIcon'></i> &nbsp;{lang="loading"}</span>
						</li>
					</ul>
				</div>
				<div id='elTemplateEditor_outerPanelWrap'>
					<div id='elTemplateEditor_panelWrap'>
						<ul id='elTemplateEditor_tabbar' class='ipsTabs ipsClearfix acpFormTabBar' data-ipsTabBar data-ipsTabBar-contentArea='#elTemplateEditor_panels'>
							{{if $current['type'] == 'templates'}}
								<li data-fileid='{$template['TemplateKey']}'>
									<a href='#' class='ipsTabs_item' id='tab_{$template['TemplateKey']}'>{$current['template']} <span data-action='closeTab'><i class='fa fa-times'></i></span></a>
								</li>
							{{else}}
								<li data-fileid='{$template['jsDataKey']}'>
									<a href='#' class='ipsTabs_item' id='tab_{$template['jsDataKey']}'>{$template['css_name']} <span data-action='closeTab'><i class='fa fa-times'></i></span></a>
								</li>
							{{endif}}
						</ul>
						<section data-role="templatePanelWrap" id='elTemplateEditor_panels'>
							{{if $current['type'] == 'templates'}}
								{template="templateEditorHtmlPane" params="$theme, $templateNames, $template, $current" app="core" location="admin" group="customization"}
							{{else}}
								{template="templateEditorCssPane" params="$theme, $templateNames, $template, $current" app="core" location="admin" group="customization"}
							{{endif}}
						</section>
					</div>
				</div>
			</div>
		</div>
		<br>
		<div id='elTemplateEditor_variablesDialog' class='ipsHide'>
			<div data-controller='core.admin.templates.variablesDialog'>
				<div class='ipsPad'>
					<p class='ipsType_textBlock'>
						{lang="theme_template_variables_info"}
					</p>
					<br>
					<textarea class='ipsField_fullWidth' data-role='variables' placeholder='{lang="theme_template_variables"}'></textarea>
					<input type='hidden' name='_variables_fileid' value=''>
					<input type='hidden' name='_variables_type' value=''>
				</div>
				<div class='ipsPad ipsAreaBackground ipsType_right'>
					<input type='submit' class='ipsButton ipsButton_primary' value='{lang="save"}'>
				</div>
			</div>
		</div>

		<div id='elTemplateEditor_attributesDialog' class='ipsHide'>
			<div data-controller='core.admin.templates.variablesDialog'>
				<div class='ipsPad'>
					<p class='ipsType_textBlock'>
						{lang="theme_css_attributes"}
					</p>
					<br>
					<input class='ipsField_fullWidth' data-role='variables' placeholder="e.g. media='screen'">
					<input type='hidden' name='_variables_fileid' value=''>
					<input type='hidden' name='_variables_type' value=''>
				</div>
				<div class='ipsPad ipsAreaBackground ipsType_right'>
					<input type='submit' class='ipsButton ipsButton_primary' value='{lang="save"}'>
				</div>
			</div>
		</div>
	</div>
</form>
<ul class='ipsList_inline ipsType_light ipsType_small' id='elTemplateEditor_info'>
	<li class='cTemplateState_outofdate'> {lang="theme_template_outofdate"}</li>
	<li class='cTemplateState_changed'> {lang="theme_template_modified"}</li>
	<li class='cTemplateState_inherit'> {lang="theme_template_inherited"}</li>
	<li class='cTemplateState_custom'> {lang="theme_template_unique"}</li>
</ul>