<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-itemID='{expression="\IPS\Request::i()->id"}'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	<div class='ipsBox'>
		<div class='ipsPad'>
			<h3 class='ipsType_sectionHead'>{lang="emailtpl_title"}</h3>
			<p class='ipsType_reset ipsType_normal'>
				{lang="emailtpl_info"}
			</p>
		
			<hr class='ipsHr'>
		
			<ul class='ipsForm ipsForm_vertical'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $inputName => $input}}
						{{if is_object( $input ) }}
							{$input->rowHtml($form)|raw}
						{{else}}
							{$input|raw}
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
		</div>
		<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
			{expression="implode( '', $actionButtons)" raw="true"}
		</div>
	</div>
</form>