<ips:template parameters="$id, $action, $tabs, $hiddenValues, $actionButtons, $uploadField, $formClass='', $attributes=array(), $sidebar, $form, $errorTabs" />
<div data-controller='core.admin.members.moderatorPermissions'>
	<form accept-charset='utf-8' data-formId="{$id}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm class="{$formClass}" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}}>
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			{{if is_array($v)}}
				{{foreach $v as $_v}}
					<input type="hidden" name="{$k}[]" value="{$_v}">
				{{endforeach}}
			{{else}}
				<input type="hidden" name="{$k}" value="{$v}">
			{{endif}}
		{{endforeach}}
		{{if $uploadField}}
			<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		{{endif}}
		<div class='ipsBox ipsSpacer_bottom'>
			<div class='acpFormTabContent'>
				<ul class='ipsForm {$formClass}'>
					{{foreach $tabs[''] as $input}}
						{$input->rowHtml( $form )|raw}
					{{endforeach}}
				</ul>
			</div>
		</div>
		<div id='permission_form_wrapper'>
			<div class="ipsClearfix">
				<div class="ipsJS_show ipsSpacer_bottom ipsSpacer_half">
					<ul class="ipsList_inline ipsList_noSpacing">
						<li><a href="#" class="ipsButton ipsButton_veryLight ipsButton_verySmall" data-role="checkAll">{lang="check_all"}</a></li>
						<li><a href="#" class="ipsButton ipsButton_veryLight ipsButton_verySmall" data-role="uncheckAll">{lang="uncheck_all"}</a></li>
					</ul>
				</div>
			</div>
			<div class='ipsBox'>
				{{if $form->error}}
					<div class="ipsMessage ipsMessage_error">
						{$form->error}
					</div>
				{{endif}}
				{{if !empty( $errorTabs )}}
					<p class="ipsMessage ipsMessage_error ipsJS_show">{lang="tab_error"}</p>
				{{endif}}
				<div class='ipsTabs ipsClearfix ipsJS_show acpFormTabBar' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
					<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
					<ul role='tablist'>
						{{foreach $tabs as $name => $content}}
							{{if $name}}
								<li>
									<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item {{if in_array( $name, $errorTabs )}}ipsTabs_error{{endif}}" role="tab" aria-selected="false">
										{{if in_array( $name, $errorTabs )}}<i class="fa fa-exclamation-circle"></i> {{endif}}{lang="$name"}
									</a>
								</li>
							{{endif}}
						{{endforeach}}
					</ul>
				</div>
				<div id='ipsTabs_content_{$id}' class='acpFormTabContent'>
					{{foreach $tabs as $name => $collection}}
						{{if $name}}
							<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
								<ul class='ipsForm {$formClass}'>
									{{foreach $collection as $input}}
										{$input->rowHtml( $form )|raw}
									{{endforeach}}
								</ul>
							</div>
						{{endif}}
					{{endforeach}}
				</div>
			</div>
		</div>
		<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
			{expression="implode( '', $actionButtons )" raw="true"}
		</div>
	</div>
</form>