<ips:template parameters="" />
<div id='acpWarnings'>
	<div class='ipsAreaBackground_light ipsPad'>
		<div>
			<h2 class='ipsType_sectionHead'><strong>{lang="profile_complete_quick_register_off_title"}</strong></h2>
			<div class='ipsType_normal ipsType_reset'>
				{lang="profile_complete_quick_register_off"}
				<ul class='ipsToolList ipsToolList_horizontal ipsAlert_buttonRow ipsClear ipsClearfix'>
					<li class="ipsPos_left"><a href="{url="app=core&module=membersettings&controller=profilecompletion&do=enableQuickRegister"}" class="ipsButton ipsButton_primary">{lang="profile_complete_quick_register_off_button"}</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>