<ips:template parameters="$rows" />
{{if count( $rows )}}
	<div class='ipsDataList'>
		{{foreach $rows as $row}}
			<div class='ipsDataItem ipsDataItem_fullWidth'>
				<div class='ipsDataItem_generic ipsDataItem_size7'>
					{{if $row['complete'] === NULL}}
						<div class="ipsProgressBar ipsProgressBar_small ipsProgressBar_fullWidth ipsProgressBar_animated"><div class="ipsProgressBar_progress" style="width:100%">{lang="progress_bar_percent_not_available"}</div></div>
					{{else}}
						<div class="ipsProgressBar ipsProgressBar_small ipsProgressBar_fullWidth"><div class="ipsProgressBar_progress" style="width: {expression="number_format( $row['complete'], 2)" }%">{$row['complete']}%</div></div>
					{{endif}}
				</div>
				<div class='ipsDataItem_title'>
					<span class='ipsType_medium ipsType_reset ipsSpacer_bottom ipsSpacer_half ipsTruncate ipsTruncate_line'><strong>{$row['text']|raw}</strong></span>
				</div>
			</div>
		{{endforeach}}
	</div>
	<p class="ipsType_medium ipsType_light ipsType_center">
		{{if settings.task_use_cron == 'normal'}}
			{lang="background_processes_desc_nocron"}
		{{else}}
			{lang="background_processes_desc"}
		{{endif}}
		{{if !\IPS\CIC}}
			<br>
			{lang="background_processes_run_now" sprintf="\IPS\Member::loggedIn()->language()->addToStack('background_process_run_title')"}
		{{endif}}
	</p>
{{else}}
	<div class="ipsType_medium ipsType_light ipsType_center">
		{lang="no_background_processes"}
	</div>
{{endif}}
