<ips:template parameters="$table, $headers, $rows" />
{{if empty( $rows )}}
	<tr>
		<td colspan="{expression="count( $headers )"}">
			<div class='ipsPad_double ipsType_light'>
				{lang="no_results"}
				{{if isset( $table->rootButtons['add'] )}}
				&nbsp;&nbsp;
				<a
					{{if isset( $table->rootButtons['add']['link'] )}}href='{$table->rootButtons['add']['link']}'{{endif}}
					title='{lang="$table->rootButtons['add']['title']"}'
					class='ipsButton ipsButton_alternate ipsButton_small {{if isset( $table->rootButtons['add']['class'] )}}{$table->rootButtons['add']['class']}{{endif}}'
					role="button"
					{{if isset( $table->rootButtons['add']['data'] )}}
						{{foreach $table->rootButtons['add']['data'] as $k => $v}}
							data-{$k}="{$v}"
						{{endforeach}}
					{{endif}}
					{{if isset( $table->rootButtons['add']['hotkey'] )}}
						data-keyAction='{$table->rootButtons['add']['hotkey']}'
					{{endif}}
					>{lang="$table->rootButtons['add']['title']"}</a>
				{{endif}}
			</div>
		</td>
	</tr>
{{else}}
	{{foreach $rows as $r}}
		<tr class='ipsClearfix' data-keyNavBlock {{if isset( $r['_buttons']['view'] )}}data-tableClickTarget="view"{{elseif isset( $r['_buttons']['edit'] )}}data-tableClickTarget="edit"{{endif}}>
			{{foreach $r as $k => $v}}
				{{if $k != 'attach_id'}}
					<td class='{{if $k === ( $table->mainColumn ?: $table->quickSearch )}}ipsTable_wrap{{endif}} {{if $k === $table->mainColumn}}ipsTable_primary{{endif}} {{if $k === '_buttons'}}ipsTable_controls{{endif}}{{if isset( $table->rowClasses[ $k ] )}}{expression="implode( ' ', $table->rowClasses[ $k ] )"}{{endif}}' {{if $k !== $table->mainColumn && $k !== '_buttons' && $k !== 'photo'}}data-title="{lang="{$table->langPrefix}{$k}"}"{{endif}}>
						{{if $k === '_buttons'}}
							{template="controlStrip" params="$v" group="global" app="core"}
						{{else}}
							{$v|raw}
						{{endif}}
					</td>
				{{endif}}
			{{endforeach}}
			{{if member.hasAcpRestriction( 'core', 'overview', 'files_delete' )}}
				<td class='cFilesTable_multimod'>
					<span class='ipsCustomInput'>
						<input type="checkbox" name="multimod[{$r['attach_id']}]" value="1" data-role="moderation" data-actions="delete" data-state>
						<span></span>
					</span>
				</td>
			{{endif}}
		</tr>
	{{endforeach}}
{{endif}}