<ips:template parameters="$member" />
{{if \IPS\Settings::i()->timeSpent_viewGroups =='all' or \IPS\Member::loggedIn()->inGroup( explode( ',', \IPS\Settings::i()->timeSpent_viewGroups ) )}}
	{{$totalTime = $member->time_spent > 0 ? \IPS\Member::loggedIn()->getTotalTimeSpentOnline( $member, $member->time_spent, FALSE ) : 0;}}
	{{if $totalTime}}
		<li class="ipsDataItem">
			<span class="ipsDataItem_generic ipsDataItem_size3">
				<strong>
					{lang="time_spent"}
				</strong>
			</span>
			<span class="ipsDataItem_main">
				{$totalTime}
			</span>
		</li>	
	{{endif}}
{{endif}}