<ips:template parameters="$key" />
{{$handler = NULL;}}
{{if is_numeric( $key )}}
	{{try { $handler = \IPS\Login\Handler::load( $key ); } catch( \Exception $e ) { $handler = NULL; } }}
{{elseif $key}}
	{{$handlers = \IPS\Login::handlers( TRUE );}}
{{if isset( $handlers[ $key ] )}}
		{{$handler = $handlers[ $key ];}}
	{{endif}}
{{endif}}
{{if $handler}}
	{$handler->_title}
{{elseif $key}}
	{$key}
{{else}}
	<em class="ipsType_light" title='{lang="device_handler_unknown_desc"}' data-ipsTooltip>{lang="device_handler_unknown"}</em>
{{endif}}