<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
<form accept-charset='utf-8' method="post" action="{$action}" id='elStatusSubmit' {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<div class="ipsPad">
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endforeach}}
		{{if $uploadField}}
			<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
			<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
		{{endif}}
		{{foreach $elements as $collection}}
			{{foreach $collection as $input}}
				{{if $input instanceof \IPS\Helpers\Form\Editor}}
					{$input->html()|raw}
					{{if $input->error}}
						<br>
						<span class="ipsType_warning">{lang="$input->error"}</span>
					{{endif}}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</div>
	<ul class="ipsPad ipsToolList ipsToolList_horizontal ipsList_reset ipsClearfix ipsAreaBackground">
		{{foreach $actionButtons as $button}}
			<li>{$button|raw}</li>
		{{endforeach}}
		{{foreach $elements as $collection}}
			{{foreach $collection as $input}}
			{{if $input instanceof \IPS\Helpers\Form\Checkbox}}
					<li class='ipsPos_left ipsResponsive_noFloat {{if !($input instanceof \IPS\Helpers\Form\Captcha)}}ipsComposeArea_formControl{{endif}} ipsType_small'>
						{$input->html()|raw}
						<label for="check_{$input->htmlId}">
							{lang="$input->name"}
						</label>
						{{if $input->error}}
							<div class="ipsType_warning ipsSpacer_top" data-role="commentFormError">{lang="$input->error"}</div>
						{{endif}}
					</li>
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</ul>
</form>	
