<ips:template parameters="$id, $text, $currentStatus, $ad" />
{{$filter = \IPS\Request::i()->filter;}}
{{if $currentStatus === -1}}
	<span class='ipsBadge ipsBadge_negative'>{lang="$text"}</span>
{{elseif ( $ad['ad_end'] AND $ad['ad_end'] < time() ) OR ( $ad['ad_maximum_unit'] == 'i' AND $ad['ad_maximum_value'] > -1 AND $ad['ad_impressions'] >= $ad['ad_maximum_value'] ) OR ( $ad['ad_maximum_unit'] == 'c' AND $ad['ad_maximum_value'] > -1 AND $ad['ad_clicks'] >= $ad['ad_maximum_value'] ) }}
	<span class='ipsBadge ipsBadge_neutral' data-ipsTooltip title='{lang="ad_nostatus_change"}'>{lang="disabled"}</span>
{{else}}
	<span data-ipsStatusToggle>
		<a href="{url="app=core&module=promotion&controller=advertisements&do=toggle&id=$id&status=0&filter={$filter}"}" data-ipsTooltip title="{lang="set_inactive"}" {{if $currentStatus !== 1}}class='ipsHide'{{endif}} data-state="enabled">
			<span class='ipsBadge ipsBadge_positive'>
				{lang="enabled"}
			</span>
		</a>
		<a href="{url="app=core&module=promotion&controller=advertisements&do=toggle&id=$id&status=1&filter={$filter}"}" data-ipsTooltip title="{lang="set_active"}" {{if $currentStatus !== 0}}class='ipsHide'{{endif}} data-state="disabled">
			<span class='ipsBadge ipsBadge_negative'>
				{lang="disabled"}
			</span>
		</a>
	</span>
{{endif}}