<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<div>
	<div>
		<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-itemID='{expression="\IPS\Request::i()->id"}'>
			<input type="hidden" name="{$id}_submitted" value="1">
			{{foreach $hiddenValues as $k => $v}}
				{{if is_array($v)}}
					{{foreach $v as $_k => $_v}}
						<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
					{{endforeach}}
				{{else}}
					<input type="hidden" name="{$k}" value="{$v}">
				{{endif}}
			{{endforeach}}
			{{if $uploadField}}
				<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
				<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
			{{endif}}
			
			{{if isset( $elements['']['menu_manager_extension'])}}
				<div class='ipsFieldRow_section'>{lang="menu_item_type"}</div>
				{{$elem = $elements['']['menu_manager_extension'];}}
				{{$options = $elem->options['options'];}}
				{{$leftOver = count( $options ) % 3;}}
				{{$perCol1 = $perCol2 = $perCol3 = ( count( $options ) - $leftOver ) / 3;}}
				{{if $leftOver >= 1}}
					{{$perCol1++;}}
				{{elseif $leftOver == 2}}
					{{$perCol2++;}}
				{{endif}}
				<div class='ipsPad ipsAreaBackground_reset'>
					<div class='ipsGrid ipsGrid_collapsePhone' data-ipsSideMenu data-ipsSideMenu-type='radio'>
						{template="menuManagerTypeColumn" group="applications" app="core" params="array_slice( $options, 0, $perCol1 ), $elem->value, $elem->options['disabled'], $elem->options['toggles']"}
						{template="menuManagerTypeColumn" group="applications" app="core" params="array_slice( $options, $perCol1, $perCol2 ), $elem->value, $elem->options['disabled'], $elem->options['toggles']"}
						{template="menuManagerTypeColumn" group="applications" app="core" params="array_slice( $options, ( $perCol1 + $perCol2 ) ), $elem->value, $elem->options['disabled'], $elem->options['toggles']"}
					</div>
				</div>
			{{endif}}
			<div class='ipsFieldRow_section'>{lang="menu_configuration"}</div>
			<ul class='ipsList_reset ipsPad ipsAreaBackground_reset'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $inputName => $input}}
						{{if $inputName !== 'menu_manager_extension'}}
							{{if is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
			<ul class="ipsPad ipsType_center ipsList_reset ipsClearfix ipsAreaBackground_light">
				{{foreach $actionButtons as $button}}
					<li>{$button|raw}</li>
				{{endforeach}}
			</ul>
		</form>
	</div>
</div>