<ips:template parameters="" />
<div class="ipsPad">
	<div class="ipsSpacer_bottom ipsSpacer_double">
		<p class="ipsType_normal">{lang="google_adsense_blurb"}</p>
	</div>
	
	<div class="ipsSpacer_bottom ipsSpacer_double">
		<h2 class="ipsType_sectionHead">{lang="google_adsense_login_header"}</h2>
		<p class="ipsType_normal">{lang="google_adsense_login_blurb"}</p>
		<a href='{url="secure-ads-adsense" ips="true"}' class="ipsButton ipsButton_normal" target='_blank'>{lang="google_adsense_login_link"}</a>
	</div>
	
	<div class="ipsSpacer_bottom ipsSpacer_double">
		<h2 class="ipsType_sectionHead">{lang="google_adsense_ajax_header"}</h2>
		<p class="ipsType_normal">{lang="google_adsense_ajax_intro"}</p>
		<p class="ipsType_normal">{lang="google_adsense_ajax_blurb"}</p>
		<ol>
			<li class="ipsType_normal">{lang="google_adsense_ajax_ins_1"}</li>
			<li class="ipsType_normal">{lang="google_adsense_ajax_ins_2"}</li>
			<li class="ipsType_normal">{lang="google_adsense_ajax_ins_3"}</li>
			<li class="ipsType_normal">{lang="google_adsense_ajax_ins_4"}</li>
		</ol>
	</div>
	
	<p class="ipsType_normal">{lang="google_adsense_other"}</p>
</div>