<ips:template parameters="$member, $history, $historyFilters" />
<div id='elMemberHistory' data-controller="core.admin.members.history">
	<h2 class='ipsType_sectionTitle ipsType_reset ipsClearfix'>
		<a href='#memberHistoryFilters_menu' id='memberHistoryFilters' data-ipsMenu>
			<span data-role="historyTitle">{lang="all_recent_account_activity"}</span>
			<span class="ipsPos_right"><i class="fa fa-caret-down"></i></span>
		</a>
	</h2>
	<div id='memberHistoryFilters_menu' class='ipsMenu ipsHide'>
		<ul>
			{{$logApp = NULL;}}
			{{foreach $historyFilters as $filter}}		
				{{if $logApp != $filter['log_app']}}
					<li class="ipsMenu_title">{lang="memberlog_app_{$filter['log_app']}"}</li>
					{{$logApp = $filter['log_app'];}}
				{{endif}}
				<li class="ipsMenu_item" data-ipsMenuValue="{$filter['log_app']}_{$filter['log_type']}"><a href="{url="app=core&module=members&controller=members&do=history&id={$member->member_id}&advanced_search_submitted=1&log_type={$filter['log_type']}&_fromFilter=1" csrf="true"}">{lang="log_type_title_{$filter['log_type']}"}</a></li>
			{{endforeach}}
			<li class="ipsMenu_sep"><hr></li>
			<li class="ipsMenu_item" data-ipsMenuValue=""><a href="{url="app=core&module=members&controller=members&do=history&id={$member->member_id}&_fromFilter=1"}">{lang="all_recent_account_activity"}</a></li>
		</ul>
	</div>
	<div class="ipsPad" data-role="historyDisplay">
		{$history|raw}
	</div>
</div>