<ips:template parameters="$member, $block, $title, $tabNames, $activeId, $defaultContent, $editLink" />
<div class='ipsBox ipsSpacer_bottom ipsSpacer_double'>
	{{if $title !== NULL}}
		<h2 class='ipsBox_titleBar ipsType_reset'>
			{{if $editLink and member.hasAcpRestriction( 'core', 'members', 'member_edit' ) and ( !$member->isAdmin() or member.hasAcpRestriction( 'core', 'members', 'member_edit_admin' ) )}}
				<a href="{$editLink}" class="ipsPos_right ipsType_medium" data-ipsDialog data-ipsDialog-title="{lang="$title"}">{lang="edit"}</a>
			{{endif}}
			{lang="$title"}
		</h2>
	{{endif}}
	{{if count( $tabNames ) > 1}}
		<div class='ipsTabs ipsTabs_contained ipsTabs_small ipsClearfix' id='elTabs_{expression="md5( $block )"}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{expression="md5( $block )"}' {{if \IPS\Request::i()->isAjax()}}data-ipsTabBar-updateURL='false'{{endif}}>
			<a href='#elTabs_{expression="md5( $block )"}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'>
				{{foreach $tabNames as $i => $name}}
					<li>
						<a href='{$member->acpUrl()->setQueryString( array( 'do' => 'view', 'blockKey' => $block, 'block[' . $block . ']' => $i ) )}' id='{expression="md5( $block )"}_tab_{$i}' class="ipsTabs_item {{if $i == $activeId}}ipsTabs_activeItem{{endif}}" {{if is_array( $name )}}title='{lang="{$name[1]}"}' data-ipsTooltip{{else}}title='{lang="{$name}"}'{{endif}} role="tab" aria-selected="{{if $i == $activeId}}true{{else}}false{{endif}}">
							{{if is_array( $name )}}
								<i class="fa fa-{$name[0]}"></i>
							{{else}}
								{lang="$name"}
							{{endif}}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<section id='ipsTabs_content_{expression="md5( $block )"}'>
	{{endif}}
		{{foreach $tabNames as $i => $name}}
			{{if $i == $activeId}}
				<div id='ipsTabs_elTabs_{expression="md5( $block )"}_{expression="md5( $block)"}_tab_{$i}_panel' class="ipsTabs_panel" aria-labelledby="{expression="md5( $block )"}_tab_{$i}" aria-hidden="false">
					{$defaultContent|raw}
				</div>
			{{endif}}
		{{endforeach}}
	{{if count( $tabNames ) > 1}}
		</section>
	{{endif}}
</div>
