<ips:template parameters=" " />
{{if theme.volpe_sc10_header or theme.volpe_sc10_content or theme.volpe_sc10_buttons}}
<div class="swiper-slide slide-10">
	<div class="swiper-lazy" data-background="{theme='volpe_sc10_bgimage'}">
		<article class="align-{theme='volpe_sc10_align'}">
			<div class="slide-content">
				{{if theme.volpe_sc10_header}}<h2 class="sheader">{theme="volpe_sc10_header"}</h2>{{endif}}
				{{if theme.volpe_sc10_content}}<div class="scontent">{theme="volpe_sc10_content"}</div>{{endif}}
				{{if theme.volpe_sc10_buttons}}<div class="sbuttons">{theme="volpe_sc10_buttons"}</div>{{endif}}
			</div>
		</article>
	</div>
</div>
{{endif}}