<ips:template parameters=" " />
{{if theme.volpe_sc3_header or theme.volpe_sc3_content or theme.volpe_sc3_buttons}}
<div class="swiper-slide slide-3">
	<div class="swiper-lazy" data-background="{theme='volpe_sc3_bgimage'}">
		<article class="align-{theme='volpe_sc3_align'}">
			<div class="slide-content">
				{{if theme.volpe_sc3_header}}<h2 class="sheader">{theme="volpe_sc3_header"}</h2>{{endif}}
				{{if theme.volpe_sc3_content}}<div class="scontent">{theme="volpe_sc3_content"}</div>{{endif}}
				{{if theme.volpe_sc3_buttons}}<div class="sbuttons">{theme="volpe_sc3_buttons"}</div>{{endif}}
			</div>
		</article>
	</div>
</div>
{{endif}}