<ips:template parameters=" " />
{template="volpe_slide1" app="core" group="volpe" params="" if="theme.volpe_sc1_turn == '1' and theme.volpe_sc1_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc1_wcs))"}
{template="volpe_slide2" app="core" group="volpe" params="" if="theme.volpe_sc2_turn == '1' and theme.volpe_sc2_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc2_wcs))"}
{template="volpe_slide3" app="core" group="volpe" params="" if="theme.volpe_sc3_turn == '1' and theme.volpe_sc3_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc3_wcs))"}
{template="volpe_slide4" app="core" group="volpe" params="" if="theme.volpe_sc4_turn == '1' and theme.volpe_sc4_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc4_wcs))"}
{template="volpe_slide5" app="core" group="volpe" params="" if="theme.volpe_sc5_turn == '1' and theme.volpe_sc5_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc5_wcs))"}
{template="volpe_slide6" app="core" group="volpe" params="" if="theme.volpe_sc6_turn == '1' and theme.volpe_sc6_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc6_wcs))"}
{template="volpe_slide7" app="core" group="volpe" params="" if="theme.volpe_sc7_turn == '1' and theme.volpe_sc7_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc7_wcs))"}
{template="volpe_slide8" app="core" group="volpe" params="" if="theme.volpe_sc8_turn == '1' and theme.volpe_sc8_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc8_wcs))"}
{template="volpe_slide9" app="core" group="volpe" params="" if="theme.volpe_sc9_turn == '1' and theme.volpe_sc9_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc9_wcs))"}
{template="volpe_slide10" app="core" group="volpe" params="" if="theme.volpe_sc10_turn == '1' and theme.volpe_sc10_wcs =='*' or member.loggedIn()->inGroup( explode(',',theme.volpe_sc10_wcs))"}