<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class='ipsDataItem'>
		{{$idField = $row::$databaseColumnId;}}
		<article id='elComment_{$row->$idField}' class='ipsComment {{if \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $row->reactionCount() >= settings.reputation_highlight}}ipsComment_popular{{endif}} ipsComment_parent ipsClearfix ipsClear {{if $row->hidden()}}ipsModerated{{endif}}'>
			
			{{if \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $row->reactionCount() >= settings.reputation_highlight}}
				<strong class='ipsComment_popularFlag' data-ipsTooltip title='{lang="this_is_a_popular_comment"}'><i class='fa fa-heart'></i></strong>
			{{endif}}

			<div id='comment-{$row->$idField}_wrap' class='ipsComment_content ipsType_normal ipsClearfix'>
				{{if $table->canModerate() and ( $row->canSplit() or ( $row->hidden() === -1 AND $row->canUnhide() ) or ( $row->hidden() === 1 AND $row->canUnhide() ) or $row->canDelete() )}}
					<div class='ipsDataItem_modCheck ipsPos_right'>
						<span class='ipsCustomInput'>
							<input type="checkbox" name="moderate[{$row->$idField}]" value="1" data-role="moderation" data-actions="{{if $row->canSplit()}}split{{endif}} {{if $row->hidden() === -1 AND $row->canUnhide()}}unhide{{elseif $row->hidden() === 1 AND $row->canUnhide()}}approve{{elseif $row->canHide()}}hide{{endif}} {{if $row->canDelete()}}delete{{endif}}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
							<span></span>
						</span>
					</div>
				{{endif}}
				<div class='ipsComment_header'>
					{{if $table->canModerate() and ( $row->canSplit() or ( $row->hidden() === -1 AND $row->canUnhide() ) or ( $row->hidden() === 1 AND $row->canUnhide() ) or $row->canDelete() )}}
						<div class='ipsComment_header_modcbox'>
					{{endif}}
					{$row->contentTableHeader()|raw}
					{{if $table->canModerate() and ( $row->canSplit() or ( $row->hidden() === -1 AND $row->canUnhide() ) or ( $row->hidden() === 1 AND $row->canUnhide() ) or $row->canDelete() )}}
						</div>
					{{endif}}
				</div>
				
				<div class='ipsPad_half'>
					<div class='ipsAreaBackground_reset ipsPad'>
						{{if \IPS\Request::i()->controller == 'activity'}}
							<div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
								{template="userPhoto" group="global" app="core" params="$row->author(), 'mini'"}
								<div>
									<h3 class='ipsType_reset ipsType_normal'>{$row->author()->link()|raw}</h3>
						{{endif}}
						<p class='ipsComment_meta ipsType_light ipsType_medium ipsType_blendLinks'>
							<a href='{$row->url( 'find' )}' class='ipsType_blendLinks'>{$row->dateLine()|raw}</a>
							{{if $row->editLine()}}
								&middot; {$row->editLine()|raw}
							{{endif}}
							{{if $row->hidden()}}
								&middot; {$row->hiddenBlurb()}
							{{endif}}
							{{if $row->canReportOrRevoke() === TRUE}}
								&middot; <a href='{$row->url('report')}' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-size='medium' data-ipsDialog-flashMessage='{lang="report_submit_success"}' data-ipsDialog-title="{lang="report_reply"}" data-action='reportComment' title='{lang="report_content"}'><span class='ipsResponsive_showPhone ipsResponsive_inline'><i class='fa fa-flag'></i></span><span class='ipsResponsive_hidePhone ipsResponsive_inline'>{lang="report_reply"}</span></a>
							{{endif}}
						</p>
						{{if \IPS\Request::i()->controller == 'activity'}}
								</div>
							</div>
						{{endif}}
						<hr class='ipsHr'>
						<div data-role='commentContent' class='ipsType_break ipsType_richText ipsContained' data-controller='core.front.core.lightboxedImages'>
							{{if $row->hidden() === 1 && $row->author()->member_id == \IPS\Member::loggedIn()->member_id}}
								<strong class='ipsType_medium ipsType_warning'><i class='fa fa-info-circle'></i> {lang="comment_awaiting_approval"}</strong>
							{{endif}}
							{$row->content()|raw}
						</div>
						{{if $row->hidden() !== 1 && \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_enabled}}
							<div class='ipsItemControls'>
								{template="reputation" group="global" app="core" params="$row"}
							</div>
						{{endif}}
					</div>
				</div>			
			</div>
		</article>
	</li>
{{endforeach}}