<ips:template parameters="$tabNames, $activeId, $defaultContent, $url, $tabParam='tab', $tabClasses='', $panelClasses=''" />
<div class='acpBlock'>
	<div class='ipsTabs {$tabClasses} ipsClearfix acpFormTabBar' id='elTabs_{expression="md5( $url->acpQueryString() )"}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{expression="md5( $url->acpQueryString() )"}' {{if \IPS\Request::i()->isAjax()}}data-ipsTabBar-updateURL='false'{{endif}}>
		<a href='#elTabs_{expression="md5( $url->acpQueryString() )"}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role='tablist'
			{{foreach $tabNames as $i => $name}}
				<li>
					<a href='{{if $i}}{$url->setQueryString( $tabParam, $i )}{{else}}{$url}{{endif}}' id='{expression="md5( $url->acpQueryString() )"}_tab_{$i}' class="ipsTabs_item {{if $i == $activeId}}ipsTabs_activeItem{{endif}}" title='{lang="{$name}"}' role="tab" aria-selected="{{if $i == $activeId}}true{{else}}false{{endif}}">
						{lang="$name"}
						{{if \IPS\IN_DEV}}{template="searchKeywords" app="core" group="global" params="$url->setQueryString( 'tab', $i )->acpQueryString(), $name"}{{endif}}
					</a>
				</li>
			{{endforeach}}
		</ul>
	</div>
	<section id='ipsTabs_content_{expression="md5( $url->acpQueryString() )"}' class='acpFormTabContent'>
		{{foreach $tabNames as $i => $name}}
			{{if $i == $activeId}}
				<div id='ipsTabs_elTabs_{expression="md5( $url->acpQueryString() )"}_{expression="md5( $url->acpQueryString() )"}_tab_{$i}_panel' class="ipsTabs_panel {$panelClasses}" aria-labelledby="{expression="md5( $url->acpQueryString() )"}_tab_{$i}" aria-hidden="false">
					{$defaultContent|raw}
				</div>
			{{endif}}
		{{endforeach}}
	</section>
</div>