<ips:template parameters="$name" />
<div data-ipsEditor-toolList data-ipsEditor-toolListMinimized data-name="{$name}" class="ipsAreaBackground_light ipsClearfix ipsHide">
	<div data-role='attachmentArea'>
		<div class="ipsComposeArea_dropZone ipsComposeArea_dropZoneSmall ipsClearfix">
			<i class='fa fa-paperclip'></i>
			<div class='ipsType_light ipsType_normal'>
				{lang="loading"}
			</div>
		</div>		
	</div>
</div>