<ips:template parameters="$dateRange, $element" />
<input name="{$element->name}[2]" value='range' type='radio' id='{$element->name}[3]_radio' data-control="toggle" data-toggles=""{{if !$element->value[1]}} checked{{endif}}> 
{$dateRange->html()|raw}
<br>
<input name="{$element->name}[2]" value='days' type='radio' id='{$element->name}[3]_radio'{{if $element->value[1]}} checked{{endif}}> 
{lang="or_more_than"}
{template="number" location="global" app="core" group="forms" params="$element->name . '[1]', $element->value[1], $element->required, NULL, FALSE, 0, NULL, 1, 0, NULL, FALSE, \IPS\Member::loggedIn()->language()->addToStack( 'days_ago' ), array(), TRUE, array(), $element->name . '_number'"}
<br>
<input name="{$element->name}[2]" value='days_lt' type='radio' id='{$element->name}[3]_radio'{{if ! empty( $element->value[3])}} checked{{endif}}> 
{lang="or_less_than"}
{template="number" location="global" app="core" group="forms" params="$element->name . '[3]', isset( $element->value[3] ) ? $element->value[3] : NULL, $element->required, NULL, FALSE, 0, NULL, 1, 0, NULL, FALSE, \IPS\Member::loggedIn()->language()->addToStack( 'days_ago' ), array(), TRUE, array(), $element->name . '_number_lt'"}