<ips:template parameters="" />
<div class="ipsPad">
	{lang="utf8mb4_converter_conf_intro"}
	<ol>
		<li>{lang="utf8mb4_converter_conf_1" sprintf="\IPS\ROOT_PATH"}</li>
		<li>
			{lang="utf8mb4_converter_conf_2"}
			<pre class="ipsCode">'sql_utf8mb4' => false,</pre>
			{lang="utf8mb4_converter_conf_2b"}
			<pre class="ipsCode">\$INFO['sql_utf8mb4'] = false;</pre>
		</li>
		<li>{lang="utf8mb4_converter_conf_3"}</li>
	</ol>
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a class="ipsButton ipsButton_primary" href="{url="app=core&module=support&controller=utf8mb4"}">{lang="utf8mb4_converter_finish"}</a>
</div>