<ips:template parameters="" />
<meta charset="utf-8">
{{if theme.responsive}}
	<meta name="viewport" content="width=device-width, initial-scale=1">
{{endif}}
{{if !isset( \IPS\Output::i()->metaTags['og:image'] ) and \IPS\Theme::i()->logo_sharer }}
	<meta property="og:image" content="{theme="logo_sharer"}">
{{endif}}
{{if !isset( \IPS\Output::i()->metaTags['og:image'] ) and !\IPS\Theme::i()->logo_sharer  }}
	<meta name="twitter:card" content="summary" />
{{else}}
	<meta name="twitter:card" content="summary_large_image" />
{{endif}}
{{if \IPS\Settings::i()->site_twitter_id}}
	{{if mb_substr( \IPS\Settings::i()->site_twitter_id, 0, 1 ) === '@'}}
		<meta name="twitter:site" content="{setting="site_twitter_id"}" />
	{{else}}
		<meta name="twitter:site" content="@{setting="site_twitter_id"}" />
	{{endif}}
{{endif}}
{{foreach \IPS\Output::i()->metaTags as $name => $content}}
	{{if $name == 'canonical'}}
		<link rel="canonical" href="{$content}">
	{{else}}
		{{if $name != 'title'}}
			{{if is_array( $content ) }}
				{{foreach $content as $_value }}
					<meta {{if mb_substr( $name, 0, 3 ) === 'og:' or mb_substr( $name, 0, 3 ) === 'fb:'}}property{{else}}name{{endif}}="{$name}" content="{$_value}">
				{{endforeach}}
			{{else}}
				<meta {{if mb_substr( $name, 0, 3 ) === 'og:' or mb_substr( $name, 0, 3 ) === 'fb:'}}property{{else}}name{{endif}}="{$name}" content="{$content}">
			{{endif}}
		{{endif}}
	{{endif}}
{{endforeach}}
<meta name="theme-color" content="{theme="header"}">
{{foreach \IPS\Output::i()->linkTags as $type => $value}}
	{{if is_array( $value )}}
		<link {{foreach $value as $k => $v}}{$k}="{expression="$v"}" {{endforeach}}/>
	{{elseif $type != 'canonical' OR !isset( \IPS\Output::i()->metaTags['canonical'] )}}
		<link rel="{$type}" href="{expression="$value"}" />
	{{endif}}
{{endforeach}}
{{foreach \IPS\Output::i()->rssFeeds as $title => $url}}<link rel="alternate" type="application/rss+xml" title="{lang="$title"}" href="{$url}" />{{endforeach}}
{{if \IPS\Output::i()->base}}
	<base target="{expression="\IPS\Output::i()->base"}">
{{endif}}