<ips:template parameters="" />

{{if $announcements = \IPS\core\Announcements\Announcement::loadAllByLocation('content')}}
	<div class='cAnnouncementsContent'>
		{{foreach $announcements as $announcement}}
		<div class='cAnnouncementContentTop ipsMessage ipsMessage_{$announcement->color} ipsType_center'>
			<a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{$announcement->title}</a>
		</div>
		{{endforeach}}
	</div>
{{endif}}