<ips:template parameters=" " />
<ul id='elMobileNav' class='ipsList_inline ipsResponsive_hideDesktop ipsResponsive_block' data-controller='core.front.core.mobileNav'>
	{{if count( \IPS\Output::i()->breadcrumb )}}
		{{if count( \IPS\Output::i()->breadcrumb ) == 1}}
			<li id='elMobileBreadcrumb'>
				<a href='{setting="base_url"}'>
					<span>{lang="home"}</span>
				</a>
			</li>
		{{else}}
			{{$i = 0;}}
			{{foreach \IPS\Output::i()->breadcrumb as $k => $b}}
				{{if $i + 2 == count( \IPS\Output::i()->breadcrumb )}}
					<li id='elMobileBreadcrumb'>
						<a href='{$b[0]}'>
							<span>{$b[1]}</span>
						</a>
					</li>
				{{endif}}
				{{$i++;}}
			{{endforeach}}
		{{endif}}
	{{endif}}
	
	{{$defaultStream = \IPS\core\Stream::defaultStream();}}
	<li {{if !\IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'discover' ) ) }}class='ipsHide'{{endif}}>
		<a data-action="defaultStream" class='ipsType_light'  href='{{if $defaultStream}}{$defaultStream->url()}{{else}}{url="app=core&module=discover&controller=streams" seoTemplate="discover_all"}{{endif}}'><i class='icon-newspaper'></i></a>
	</li>

	{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'search' ) )}}
		<li class='ipsJS_show'>
			<a href='{url="app=core&module=search&controller=search" seoTemplate="search"}'><i class='fa fa-search'></i></a>
		</li>
	{{endif}}
	<li data-ipsDrawer data-ipsDrawer-drawerElem='#elMobileDrawer'>
		<a href='#'>
			{{$total = \IPS\Member::loggedIn()->notification_cnt;}}
			{{if !\IPS\Member::loggedIn()->members_disable_pm and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) )}}
				{{$total += \IPS\Member::loggedIn()->msg_count_new;}}
			{{endif}}
			{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) ) and \IPS\Member::loggedIn()->modPermission('can_view_reports')}}
				{{$total += \IPS\Member::loggedIn()->reportCount();}}
			{{endif}}
			{{if $total}}
				<span class='ipsNotificationCount' data-notificationType='total'>{$total}</span>
			{{endif}}
			<i class='fa fa-navicon'></i>
		</a>
	</li>
</ul>