<?php

$lang = array(
'themesetting_checkbox_bg'		=> 'CheckBox: Background',
'themesetting_checkbox_bg'		=> 'CheckBox: Background',
'themesetting_g_widget_position_top'		=> 'Кому доступно?',
'themesetting_g_widget_position_top'		=> 'Кому доступно?',
'themesetting_cat_private_ti_font_r3'		=> 'Cover title color (3)',
'themesetting_cat_private_ti_font_r3'		=> 'Cover title color (3)',
'themesetting_slider_content_title_font'		=> 'Content Title Font Color',
'themesetting_slider_content_title_font'		=> 'Content Title Font Color',
'themesetting_footer_headercolor'		=> 'Header Font Color',
'themesetting_footer_headercolor'		=> 'Header Font Color',
'themesetting_slider_overlay'		=> 'Overlay pattern',
'themesetting_slider_overlay'		=> 'Overlay pattern',
'themesetting_input_bg'		=> 'Input: Background',
'themesetting_input_bg'		=> 'Input: Background',
'themesetting_progressbar_bg'		=> 'Progres Bar background',
'themesetting_progressbar_bg'		=> 'Progres Bar background',
'themesetting_userbar_style'		=> 'Стиль юзербара',
'themesetting_userbar_style'		=> 'Стиль юзербара',
'themesetting_colorizermain'		=> 'Palette',
'themesetting_colorizermain'		=> 'Palette',
'themesetting_footer_fonthovers'		=> 'Hover colors',
'themesetting_footer_fonthovers'		=> 'Hover colors',
'themesetting_slider_loop'		=> 'Режим петли',
'themesetting_slider_loop'		=> 'Режим петли',
'themesetting_mentions'		=> 'Mentions: Background color',
'themesetting_mentions'		=> 'Mentions: Background color',
'themesetting_slider_2_title'		=> 'Заголовок',
'themesetting_slider_2_title'		=> 'Заголовок',
'themesetting_navbar_position'		=> 'Тип навигации',
'themesetting_navbar_position'		=> 'Тип навигации',
'themesetting_slider_1_content'		=> 'Наполнение',
'themesetting_slider_1_content'		=> 'Наполнение',
'themesetting_slider_effect'		=> 'Эфект скольжения',
'themesetting_slider_effect'		=> 'Эфект скольжения',
'themesetting_header_layout'		=> 'Заголовок & Слайдер & Нижний колонтитул',
'themesetting_header_layout'		=> 'Заголовок & Слайдер & Нижний колонтитул',
'themesetting_slider_height'		=> 'Slider Height (in px)',
'themesetting_slider_height'		=> 'Slider Height (in px)',
'themesetting_repscore_positivebg'		=> 'Профиль: Позитивный фон репутации',
'themesetting_repscore_positivebg'		=> 'Профиль: Позитивный фон репутации',
'themesetting_mentions_font'		=> 'Mentions: Text color',
'themesetting_mentions_font'		=> 'Mentions: Text color',
'themesetting_slider_1'		=> 'Слайдер (1)',
'themesetting_slider_1'		=> 'Слайдер (1)',
'themesetting_nt_pages_content'		=> 'Страницы Статей',
'themesetting_nt_pages_content'		=> 'Страницы Статей',
'themesetting_nt_whocansee'		=> 'Кому доступно?',
'themesetting_nt_whocansee'		=> 'Кому доступно?',
'themesetting_footer_quicklinks'		=> 'Быстрые ссылки',
'themesetting_footer_quicklinks'		=> 'Быстрые ссылки',
'themesetting_userbar_bg'		=> 'Пользовательская панель',
'themesetting_userbar_bg'		=> 'Пользовательская панель',
'themesetting_slider_4_title'		=> 'Заголовок',
'themesetting_slider_4_title'		=> 'Заголовок',
'themesetting_slider_1_wcs'		=> 'Кому доступно?',
'themesetting_slider_1_wcs'		=> 'Кому доступно?',
'themesetting_cat_ti_bg_r2'		=> 'Category Фон заголовка (2)',
'themesetting_cat_ti_bg_r2'		=> 'Category Фон заголовка (2)',
'themesetting_g_whocansee_bottom'		=> 'Кому доступно?',
'themesetting_g_whocansee_bottom'		=> 'Кому доступно?',
'themesetting_slider_enable_autoplay'		=> 'Автозапуск',
'themesetting_slider_enable_autoplay'		=> 'Автозапуск',
'themesetting_tabs_activebutton'		=> 'Tabs: Active button background',
'themesetting_tabs_activebutton'		=> 'Tabs: Active button background',
'themesetting_repscore_positivecol'		=> 'Профиль: Цвет позитивной репутации',
'themesetting_repscore_positivecol'		=> 'Профиль: Цвет позитивной репутации',
'themesetting_headerimage_hidemobile'		=> 'Header image: Hide on mobile',
'themesetting_headerimage_hidemobile'		=> 'Header image: Hide on mobile',
'themesetting_g_widget_title_bg'		=> 'Widget Фон заголовка',
'themesetting_g_widget_title_bg'		=> 'Widget Фон заголовка',
'themesetting_ipsbox_bg'		=> 'IPS Box background',
'themesetting_ipsbox_bg'		=> 'IPS Box background',
'themesetting_search_font_color'		=> 'Цвет шрифта в строке поиска',
'themesetting_search_font_color'		=> 'Цвет шрифта в строке поиска',
'themesetting_menu_borders'		=> 'Secondary Nav Bar border<span id="themesettings_desc">1px Solid border surounded on secondary menu</span>',
'themesetting_menu_borders'		=> 'Secondary Nav Bar border<span id="themesettings_desc">1px Solid border surounded on secondary menu</span>',
'themesetting_cat_private_r2'		=> 'Apply a cover (2)',
'themesetting_cat_private_r2'		=> 'Apply a cover (2)',
'themesetting_navigation_activetabbg'		=> 'Навигация, цвет активной вкладки',
'themesetting_navigation_activetabbg'		=> 'Навигация, цвет активной вкладки',
'themesetting_footer_backgroundimage_opacity'		=> 'Image Opacity',
'themesetting_footer_backgroundimage_opacity'		=> 'Image Opacity',
'themesetting_g_widget_background'		=> 'Фон блока',
'themesetting_g_widget_background'		=> 'Фон блока',
'themesetting_enable_widget_top'		=> 'Top Widget',
'themesetting_enable_widget_top'		=> 'Top Widget',
'themesetting_navbar_textalign'		=> 'Выравнивание текста навигации',
'themesetting_navbar_textalign'		=> 'Выравнивание текста навигации',
'themesetting_slider_3_content'		=> 'Наполнение',
'themesetting_slider_3_content'		=> 'Наполнение',
'themesetting_g_widget_title_top'		=> 'Заголовок',
'themesetting_g_widget_title_top'		=> 'Заголовок',
'themesetting_cat_ti_bg_gradi_r3'		=> 'Градиенты заголовка категории (3)<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_cat_ti_bg_gradi_r3'		=> 'Градиенты заголовка категории (3)<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_nt_borderseparator'		=> 'Border separator',
'themesetting_nt_borderseparator'		=> 'Border separator',
'themesetting_body_bg_imgslider'		=> 'Body: Фоновое изображение для ползунков',
'themesetting_body_bg_imgslider'		=> 'Body: Фоновое изображение для ползунков',
'themesetting_topic_author_panel'		=> 'Фон панели автора',
'themesetting_topic_author_panel'		=> 'Фон панели автора',
'themesetting_nav_active_tab'		=> 'Верхнее меню навигации active tab Background',
'themesetting_nav_active_tab'		=> 'Верхнее меню навигации active tab Background',
'themesetting_widget_bg'		=> 'Цвет блока "фоновый"<span id="themesettings_desc">Цвет для всех блоков</span>',
'themesetting_widget_bg'		=> 'Цвет блока "фоновый"<span id="themesettings_desc">Цвет для всех блоков</span>',
'themesetting_tab_panelbg'		=> 'Вкладки: фон панели',
'themesetting_tab_panelbg'		=> 'Вкладки: фон панели',
'themesetting_topic_author_panel_width'		=> 'Тема Авторская панель Ширина (в пикселях)',
'themesetting_topic_author_panel_width'		=> 'Тема Авторская панель Ширина (в пикселях)',
'themesetting_editor_tlbartabhover'		=> 'Editor Toolbar tabs Hover',
'themesetting_editor_tlbartabhover'		=> 'Editor Toolbar tabs Hover',
'themesetting_mainnav_hover'		=> 'Secondary Nav Bar hover effect',
'themesetting_mainnav_hover'		=> 'Secondary Nav Bar hover effect',
'themesetting_cat_private_r1'		=> 'Применить обложку (1)',
'themesetting_cat_private_r1'		=> 'Применить обложку (1)',
'themesetting_slider_navigation_buttons'		=> 'Показать навигацию',
'themesetting_slider_navigation_buttons'		=> 'Показать навигацию',
'themesetting_cat_private_g_r1'		=> 'Исключить из (1)',
'themesetting_cat_private_g_r1'		=> 'Исключить из (1)',
'themesetting_enable_widget_bottom'		=> 'Bottom Widget',
'themesetting_enable_widget_bottom'		=> 'Bottom Widget',
'themesetting_editor_comareabor'		=> 'Редактор Создать Границу области',
'themesetting_editor_comareabor'		=> 'Редактор Создать Границу области',
'themesetting_site_imagelogo_height'		=> 'Логотип заголовка Макс. Высота (в пикселях)<span id="themesettings_desc">В основном используется на логотипе Image</span>',
'themesetting_site_imagelogo_height'		=> 'Логотип заголовка Макс. Высота (в пикселях)<span id="themesettings_desc">В основном используется на логотипе Image</span>',
'themesetting_nt_title_bg'		=> 'Цвет вкладки "заголовок"',
'themesetting_nt_title_bg'		=> 'Цвет вкладки "заголовок"',
'themesetting_slider_2_content'		=> 'Наполнение',
'themesetting_slider_2_content'		=> 'Наполнение',
'themesetting_navbaruserbar_opacity'		=> 'Непрозрачность Navbar и Userbar',
'themesetting_navbaruserbar_opacity'		=> 'Непрозрачность Navbar и Userbar',
'themesetting_enable_slider'		=> 'Слайдер Вкл/Выкл',
'themesetting_enable_slider'		=> 'Слайдер Вкл/Выкл',
'themesetting_ipsquote_hdr'		=> 'Заголовок цитирования',
'themesetting_ipsquote_hdr'		=> 'Заголовок цитирования',
'themesetting_enable_slider_whocansee'		=> 'Кому доступно?',
'themesetting_enable_slider_whocansee'		=> 'Кому доступно?',
'themesetting_header_imgposition'		=> 'Положение фона заголовка',
'themesetting_header_imgposition'		=> 'Положение фона заголовка',
'themesetting_slider_content_background'		=> 'Фон контента<span id="themesettings_desc">Это настраиваемый блок CSS</span><span id="themesettings_desc">Вы можете использовать фон, градиенты цвета, изображения ... и т. Д.)</span><span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_slider_content_background'		=> 'Фон контента<span id="themesettings_desc">Это настраиваемый блок CSS</span><span id="themesettings_desc">Вы можете использовать фон, градиенты цвета, изображения ... и т. Д.)</span><span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_slider_3_buttons'		=> 'Кнопка на слайдере',
'themesetting_slider_3_buttons'		=> 'Кнопка на слайдере',
'themesetting_custom_editorstyle'		=> 'Изменить цвета редактора<span id="themesettings_desc">Отключите, что бы оставить редактор по умолчанию.',
'themesetting_custom_editorstyle'		=> 'Изменить цвета редактора<span id="themesettings_desc">Отключите, что бы оставить редактор по умолчанию.',
'themesetting_slider_1_title'		=> 'Заголовок',
'themesetting_slider_1_title'		=> 'Заголовок',
'themesetting_footer_bgimage'		=> 'Background Image',
'themesetting_footer_bgimage'		=> 'Background Image',
'themesetting_react_bg'		=> 'Reactions background',
'themesetting_react_bg'		=> 'Reactions background',
'themesetting_slider_4_wcs'		=> 'Кому доступно?',
'themesetting_slider_4_wcs'		=> 'Кому доступно?',
'themesetting_wrapper_bg'		=> 'Wrapper background',
'themesetting_wrapper_bg'		=> 'Wrapper background',
'theme_custom_tab_forms_toggles'		=> 'Forms & Toggles',
'theme_custom_tab_forms_toggles'		=> 'Forms & Toggles',
'themesetting_menu_hover_coloropacity'		=> 'Navigation Menus: hover color opacity',
'themesetting_menu_hover_coloropacity'		=> 'Navigation Menus: hover color opacity',
'theme_custom_tab_swiper_sliders'		=> 'Слайдеры',
'theme_custom_tab_swiper_sliders'		=> 'Слайдеры',
'themesetting_selecttree_border'		=> 'SelectTree: Border',
'themesetting_selecttree_border'		=> 'SelectTree: Border',
'themesetting_footer_aboutheader'		=> 'О нас заголовок',
'themesetting_footer_aboutheader'		=> 'О нас заголовок',
'themesetting_main_nav_font_hover'		=> 'Верхнее меню навигации Font Hover',
'themesetting_main_nav_font_hover'		=> 'Верхнее меню навигации Font Hover',
'themesetting_body_bg_repeat'		=> 'Body: Background image repeat<span id="themesettings_desc">Это поле задает повторение фонового изображения тела, вы можете использовать одно из ключевых слов.<span id="themesettings_desc"><em><strong>repeat, repeat-x, repeat-y, no-repeat</em></strong></span><span id="themesettings_desc">Это полезно, если вы хотите использовать шаблоны, а затем повторить изображение :)</span></span>',
'themesetting_body_bg_repeat'		=> 'Body: Background image repeat<span id="themesettings_desc">Это поле задает повторение фонового изображения тела, вы можете использовать одно из ключевых слов.<span id="themesettings_desc"><em><strong>repeat, repeat-x, repeat-y, no-repeat</em></strong></span><span id="themesettings_desc">Это полезно, если вы хотите использовать шаблоны, а затем повторить изображение :)</span></span>',
'themesetting_slider_image_position'		=> 'Позиции слайдера<span id="themesettings_desc">В этом поле задается начальное положение слайдерных изображений. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>left top, left center, left bottom, right top, right center, right bottom, center top, center center, center bottom</strong></em></span>',
'themesetting_slider_image_position'		=> 'Позиции слайдера<span id="themesettings_desc">В этом поле задается начальное положение слайдерных изображений. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>left top, left center, left bottom, right top, right center, right bottom, center top, center center, center bottom</strong></em></span>',
'themesetting_slider_2'		=> 'Слайдер (2)',
'themesetting_slider_2'		=> 'Слайдер (2)',
'themesetting_flashmessage_font'		=> 'Flash Message: Text color',
'themesetting_flashmessage_font'		=> 'Flash Message: Text color',
'themesetting_footer_fontcolor'		=> 'Цвет шрифта',
'themesetting_footer_fontcolor'		=> 'Цвет шрифта',
'themesetting_search_icon'		=> 'Цвет иконки "поиск"',
'themesetting_search_icon'		=> 'Цвет иконки "поиск"',
'themesetting_repscore_negativecol'		=> 'Профиль: Отрицательный цвет репутации',
'themesetting_repscore_negativecol'		=> 'Профиль: Отрицательный цвет репутации',
'themesetting_widget_borders'		=> 'Цвет рамки категорий форумов',
'themesetting_widget_borders'		=> 'Цвет рамки категорий форумов',
'themesetting_truncate_about'		=> 'Усекать "О нас"<span id="themesettings_desc">Включите, чтобы управлять количеством строк, отображаемых в «О нас», и "Readmore" кнопка</span>',
'themesetting_truncate_about'		=> 'Усекать "О нас"<span id="themesettings_desc">Включите, чтобы управлять количеством строк, отображаемых в «О нас», и "Readmore" кнопка</span>',
'themesetting_cat_private_ti_font_r1'		=> 'Цвет заголовка (1)',
'themesetting_cat_private_ti_font_r1'		=> 'Цвет заголовка (1)',
'themesetting_cat_private_g_r3'		=> 'Исключить из (3)',
'themesetting_cat_private_g_r3'		=> 'Исключить из (3)',
'themesetting_notification_readfont'		=> 'Уведомление: статус шрифта',
'themesetting_notification_readfont'		=> 'Уведомление: статус шрифта',
'themesetting_footer_background'		=> 'Background',
'themesetting_footer_background'		=> 'Background',
'themesetting_section_title_bar_border'		=> 'Выбор цвета рамки заголовка форумов',
'themesetting_section_title_bar_border'		=> 'Выбор цвета рамки заголовка форумов',
'themesetting_repscore_neutralcol'		=> 'Профиль: Цвет нейтральной репутации',
'themesetting_repscore_neutralcol'		=> 'Профиль: Цвет нейтральной репутации',
'themesetting_slider_exclude'		=> 'Исключить',
'themesetting_slider_exclude'		=> 'Исключить',
'themesetting_slider_content_title_fontsize'		=> 'Заголовок содержимого Размер шрифта (в пикселях)',
'themesetting_slider_content_title_fontsize'		=> 'Заголовок содержимого Размер шрифта (в пикселях)',
'themesetting_dialogbg'		=> 'Всплывающие окна: фоны',
'themesetting_dialogbg'		=> 'Всплывающие окна: фоны',
'themesetting_nt_hidemobile'		=> 'Скрыть на мобильном тлф?',
'themesetting_nt_hidemobile'		=> 'Скрыть на мобильном тлф?',
'themesetting_notification_readbg'		=> 'Уведомление: статус фона',
'themesetting_notification_readbg'		=> 'Уведомление: статус фона',
'themesetting_tabs_actifocolor'		=> 'Вкладки: активный текст кнопки',
'themesetting_tabs_actifocolor'		=> 'Вкладки: активный текст кнопки',
'themesetting_wrapper_border'		=> 'Цвет рамки',
'themesetting_wrapper_border'		=> 'Цвет рамки',
'themesetting_slider_2_buttons'		=> 'Кнопка на слайдере',
'themesetting_slider_2_buttons'		=> 'Кнопка на слайдере',
'themesetting_selecttree_bg'		=> 'SelectTree: Background',
'themesetting_selecttree_bg'		=> 'SelectTree: Background',
'themesetting_footer_borders'		=> 'Borders color',
'themesetting_footer_borders'		=> 'Borders color',
'themesetting_slider_3'		=> 'Слайдер (3)',
'themesetting_slider_3'		=> 'Слайдер (3)',
'themesetting_slider_enable_pagination'		=> 'Show pagenition',
'themesetting_slider_enable_pagination'		=> 'Show pagenition',
'themesetting_tabs_fontcolor'		=> 'Tabs: button text',
'themesetting_tabs_fontcolor'		=> 'Tabs: button text',
'themesetting_header_imageheight'		=> 'Высота заголовка (в пикселях)',
'themesetting_header_imageheight'		=> 'Высота заголовка (в пикселях)',
'themesetting_status_readcolor'		=> 'Статус чтения<span id="themesettings_desc">A color used on "Read" status icons</span>',
'themesetting_status_readcolor'		=> 'Статус чтения<span id="themesettings_desc">A color used on "Read" status icons</span>',
'themesetting_body_bg_size'		=> 'Body: Background size<span id="themesettings_desc">В этом поле задается размер фонового изображения тела. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>auto, 0px, 0%, cover, contain</em></strong></span>',
'themesetting_body_bg_size'		=> 'Body: Background size<span id="themesettings_desc">В этом поле задается размер фонового изображения тела. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>auto, 0px, 0%, cover, contain</em></strong></span>',
'themesetting_sidebar_bg'		=> 'Цвет блока "фонововый" для боковой панели<span id="themesettings_desc">Только для боковой панели</span>',
'themesetting_sidebar_bg'		=> 'Цвет блока "фонововый" для боковой панели<span id="themesettings_desc">Только для боковой панели</span>',
'themesetting_repscore_negativebg'		=> 'Профиль: Отрицательная репутация',
'themesetting_repscore_negativebg'		=> 'Профиль: Отрицательная репутация',
'themesetting_messages_general'		=> 'Фон сообщения: General',
'themesetting_messages_general'		=> 'Фон сообщения: General',
'themesetting_search_borders'		=> 'Поиск: закругленные углы<span id="themesettings_desc">Example: 0px 0px 0px 0px</span><span id="themesettings_desc">Top Left & Top Right x Bottom Right & Bottom left</span>',
'themesetting_search_borders'		=> 'Поиск: закругленные углы<span id="themesettings_desc">Example: 0px 0px 0px 0px</span><span id="themesettings_desc">Top Left & Top Right x Bottom Right & Bottom left</span>',
'themesetting_slider_autoplay_delay'		=> 'Скорость автовоспроизведения (в мс)',
'themesetting_slider_autoplay_delay'		=> 'Скорость автовоспроизведения (в мс)',
'themesetting_widget_title_bar_border'		=> 'Цвет рамки заголовка блоков',
'themesetting_widget_title_bar_border'		=> 'Цвет рамки заголовка блоков',
'themesetting_flashmessage_bg'		=> 'Flash Message: Background',
'themesetting_flashmessage_bg'		=> 'Flash Message: Background',
'themesetting_section_title_gradients'		=> 'Section title bar custom CSS',
'themesetting_section_title_gradients'		=> 'Section title bar custom CSS',
'themesetting_cat_ti_font_r3'		=> 'Цвет заголовка категории (3)',
'themesetting_cat_ti_font_r3'		=> 'Цвет заголовка категории (3)',
'themesetting_g_widget_title_color'		=> 'Widget title Color',
'themesetting_g_widget_title_color'		=> 'Widget title Color',
'themesetting_footer_crbackground'		=> 'Нижний колонтитул авторского права: история',
'themesetting_footer_crbackground'		=> 'Нижний колонтитул авторского права: история',
'themesetting_nt_background'		=> 'Background',
'themesetting_nt_background'		=> 'Background',
'themesetting_main_nav_uppercase'		=> 'Верхнее меню навигации: текст в верхнем регистре?',
'themesetting_main_nav_uppercase'		=> 'Верхнее меню навигации: текст в верхнем регистре?',
'themesetting_slider_content_color'		=> 'Контент, цвет шрифта',
'themesetting_slider_content_color'		=> 'Контент, цвет шрифта',
'themesetting_slider_wheretoshow'		=> 'Кому доступно?',
'themesetting_slider_wheretoshow'		=> 'Кому доступно?',
'themesetting_ipsquote_fontclr'		=> 'Цитирование, цвет шрифта',
'themesetting_ipsquote_fontclr'		=> 'Цитирование, цвет шрифта',
'themesetting_fixed_width'		=> 'Фиксированная ширина (в пикселях)',
'themesetting_fixed_width'		=> 'Фиксированная ширина (в пикселях)',
'themesetting_pagination_tabbg'		=> 'Pagination: Background',
'themesetting_pagination_tabbg'		=> 'Pagination: Background',
'themesetting_slider_article_truncatetitle'		=> 'Усекать название?',
'themesetting_slider_article_truncatetitle'		=> 'Усекать название?',
'themesetting_cat_private_ti_r3'		=> 'Название обложки (3)',
'themesetting_cat_private_ti_r3'		=> 'Название обложки (3)',
'themesetting_cat_ti_font_r1'		=> 'Цвет заголовка категории (1)',
'themesetting_cat_ti_font_r1'		=> 'Цвет заголовка категории (1)',
'themesetting_slider_4_content'		=> 'Наполнение',
'themesetting_slider_4_content'		=> 'Наполнение',
'themesetting_topic_avatar_dimensions'		=> 'Размеры аватара',
'themesetting_topic_avatar_dimensions'		=> 'Размеры аватара',
'themesetting_header_image'		=> 'Заглавное изображение',
'themesetting_header_image'		=> 'Заглавное изображение',
'themesetting_g_widget_content_bottom'		=> 'Наполнение',
'themesetting_g_widget_content_bottom'		=> 'Наполнение',
'themesetting_icontextshadow'		=> 'Тень иконки<span id="themesettings_desc">Цветная тень, используемая на значках</span>',
'themesetting_icontextshadow'		=> 'Тень иконки<span id="themesettings_desc">Цветная тень, используемая на значках</span>',
'themesetting_truncate_lines'		=> 'Усеченные линии',
'themesetting_truncate_lines'		=> 'Усеченные линии',
'themesetting_cat_id_r2'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'themesetting_cat_id_r2'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'themesetting_forum_list_border'		=> 'Список участников Цвет рамки',
'themesetting_forum_list_border'		=> 'Список участников Цвет рамки',
'themesetting_main_nav_tab'		=> 'Secondary Nav Bar background',
'themesetting_main_nav_tab'		=> 'Secondary Nav Bar background',
'theme_custom_tab_forum_categories'		=> 'Стиль форума',
'theme_custom_tab_forum_categories'		=> 'Стиль форума',
'themesetting_menu_hover_effect'		=> 'Наведение курсора на меню навигации',
'themesetting_menu_hover_effect'		=> 'Наведение курсора на меню навигации',
'themesetting_input_font'		=> 'Вход: Цвет текста',
'themesetting_input_font'		=> 'Вход: Цвет текста',
'themesetting_userbar_font_color'		=> 'Цвет шрифта пользователя',
'themesetting_userbar_font_color'		=> 'Цвет шрифта пользователя',
'themesetting_widget_title_bar'		=> 'Widget Фон заголовка',
'themesetting_widget_title_bar'		=> 'Widget Фон заголовка',
'themesetting_main_nav_fontsize'		=> 'Главная панель навигации: размер шрифта (в px)',
'themesetting_main_nav_fontsize'		=> 'Главная панель навигации: размер шрифта (в px)',
'theme_custom_tab_footer'		=> 'Нижний колонтитул',
'theme_custom_tab_footer'		=> 'Нижний колонтитул',
'themesetting_main_nav_bottomborder'		=> 'Верхнее меню навигации: Bottom border',
'themesetting_main_nav_bottomborder'		=> 'Верхнее меню навигации: Bottom border',
'theme_custom_tab_global_widgets'		=> 'Custom Widgets',
'theme_custom_tab_global_widgets'		=> 'Custom Widgets',
'themesetting_sl_customizecolor'		=> 'Использовать пользовательские цвета',
'themesetting_sl_customizecolor'		=> 'Использовать пользовательские цвета',
'themesetting_slider_5_img'		=> 'Фото слайдера',
'themesetting_slider_5_img'		=> 'Фото слайдера',
'themesetting_slider_3_img'		=> 'Фото слайдера',
'themesetting_slider_3_img'		=> 'Фото слайдера',
'themesetting_slider_2_img'		=> 'Фото слайдера',
'themesetting_slider_2_img'		=> 'Фото слайдера',
'theme_custom_tab_colorizer'		=> 'Palette',
'theme_custom_tab_colorizer'		=> 'Palette',
'themesetting_footer_toggle'		=> 'Включить дополнительный нижний колонтитул',
'themesetting_footer_toggle'		=> 'Включить дополнительный нижний колонтитул',
'themesetting_editor_areabg'		=> 'Область редактора',
'themesetting_editor_areabg'		=> 'Область редактора',
'themesetting_nt_fontcolor'		=> 'Цвет шрифта',
'themesetting_nt_fontcolor'		=> 'Цвет шрифта',
'themesetting_body_bg_gradients'		=> 'Body: Фоновые градиенты<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_body_bg_gradients'		=> 'Body: Фоновые градиенты<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_slider_5_buttons'		=> 'Кнопка на слайдере',
'themesetting_slider_5_buttons'		=> 'Кнопка на слайдере',
'themesetting_g_widget_title_bottom'		=> 'Заголовок',
'themesetting_g_widget_title_bottom'		=> 'Заголовок',
'themesetting_category_r1'		=> 'Стиль категорий форума (1)',
'themesetting_category_r1'		=> 'Стиль категорий форума (1)',
'themesetting_cat_ti_bg_gradi_r1'		=> 'Градиенты заголовка категории (1)<span id="themesettings_desc"> Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_cat_ti_bg_gradi_r1'		=> 'Градиенты заголовка категории (1)<span id="themesettings_desc"> Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_g_whocansee_top'		=> 'Кому доступно?',
'themesetting_g_whocansee_top'		=> 'Кому доступно?',
'theme_custom_tab_topic_view'		=> 'Просмотр топика',
'theme_custom_tab_topic_view'		=> 'Просмотр топика',
'themesetting_main_nav_tab_font_hover'		=> 'Secondary Nav Bar font hover',
'themesetting_main_nav_tab_font_hover'		=> 'Secondary Nav Bar font hover',
'themesetting_cat_ti_bg_r3'		=> 'Категории Фон заголовка (3)',
'themesetting_cat_ti_bg_r3'		=> 'Категории Фон заголовка (3)',
'themesetting_category_r2'		=> 'Стиль категорий форума (2)',
'themesetting_category_r2'		=> 'Стиль категорий форума (2)',
'themesetting_specific_cat_style'		=> 'Разрешить',
'themesetting_specific_cat_style'		=> 'Разрешить',
'themesetting_body_bg_image'		=> 'Сайт: Фоновое изображение',
'themesetting_body_bg_image'		=> 'Сайт: Фоновое изображение',
'themesetting_cat_id_r3'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'themesetting_cat_id_r3'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'theme_custom_tab_news_ticker'		=> 'Новостная строка',
'theme_custom_tab_news_ticker'		=> 'Новостная строка',
'themesetting_menu_hover_color'		=> 'Навигационное меню, цвет при наведении мышки',
'themesetting_menu_hover_color'		=> 'Навигационное меню, цвет при наведении мышки',
'themesetting_sl_bordercolor'		=> 'Border color',
'themesetting_sl_bordercolor'		=> 'Border color',
'themesetting_nav_active_tab_font'		=> 'Верхнее меню навигации active tab Font',
'themesetting_nav_active_tab_font'		=> 'Верхнее меню навигации active tab Font',
'themesetting_status_unreadcolor'		=> 'Непрочитанный статус<span id="themesettings_desc">Цвет, используемый для НЕ "Read" статус значков</span>',
'themesetting_status_unreadcolor'		=> 'Непрочитанный статус<span id="themesettings_desc">Цвет, используемый для НЕ "Read" статус значков</span>',
'themesetting_slider_overlayopacity'		=> 'Прозрачность наложения',
'themesetting_slider_overlayopacity'		=> 'Прозрачность наложения',
'themesetting_title_fontsize'		=> 'Заголовок: Размер шрифта (в пикселях)<span id="themesettings_desc">Размер шрифта, используемый для всех заголовков виджета и раздела</span>',
'themesetting_title_fontsize'		=> 'Заголовок: Размер шрифта (в пикселях)<span id="themesettings_desc">Размер шрифта, используемый для всех заголовков виджета и раздела</span>',
'themesetting_sl_icon_bgcolor'		=> 'Значок: Цвет фона',
'themesetting_sl_icon_bgcolor'		=> 'Значок: Цвет фона',
'themesetting_cat_ti_font_r2'		=> 'Цвет заголовка категории (2)',
'themesetting_cat_ti_font_r2'		=> 'Цвет заголовка категории (2)',
'themesetting_cat_ti_bg_gradi_r2'		=> 'Градиенты заголовка категории (2)<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_cat_ti_bg_gradi_r2'		=> 'Градиенты заголовка категории (2)<span id="themesettings_desc">Некоторые градиентные веб-сайты<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_cat_private_bg_r3'		=> 'Обложка (3)<span id="themesettings_desc">%70 прозрачный</span>',
'themesetting_cat_private_bg_r3'		=> 'Обложка (3)<span id="themesettings_desc">%70 прозрачный</span>',
'themesetting_slider_4_img'		=> 'Фото слайдера',
'themesetting_slider_4_img'		=> 'Фото слайдера',
'themesetting_nt_toggle'		=> 'Разрешить',
'themesetting_nt_toggle'		=> 'Разрешить',
'theme_custom_tab_bodytab'		=> 'Body',
'theme_custom_tab_bodytab'		=> 'Body',
'themesetting_checkbox_icon'		=> 'Checkbox: Цвет иконки',
'themesetting_checkbox_icon'		=> 'Checkbox: Цвет иконки',
'themesetting_selecttree_font'		=> 'SelectTree: Font',
'themesetting_selecttree_font'		=> 'SelectTree: Font',
'themesetting_tripestoggle'		=> 'Разрешить.<span id="themesettings_desc">Некоторые бесплатные сайты для получения текстур<span id="themesettings_desc"><a href="https://www.transparenttextures.com/" target="_blank" id="themesettings_desc_a">ПРОЗРАЧНЫЕ ТЕКСТЫ</a><a href="http://www.stripegenerator.com/" target="_blank" id="themesettings_desc_a">Генератор полос</a></span></span>',
'themesetting_tripestoggle'		=> 'Разрешить.<span id="themesettings_desc">Некоторые бесплатные сайты для получения текстур<span id="themesettings_desc"><a href="https://www.transparenttextures.com/" target="_blank" id="themesettings_desc_a">ПРОЗРАЧНЫЕ ТЕКСТЫ</a><a href="http://www.stripegenerator.com/" target="_blank" id="themesettings_desc_a">Генератор полос</a></span></span>',
'themesetting_slider_article_truncatecontent'		=> 'Усечение контента (в строках)',
'themesetting_slider_article_truncatecontent'		=> 'Усечение контента (в строках)',
'themesetting_g_widget_content_color'		=> 'Widget цвет контента',
'themesetting_g_widget_content_color'		=> 'Widget цвет контента',
'themesetting_topic_background'		=> 'Тематический фон',
'themesetting_topic_background'		=> 'Тематический фон',
'themesetting_nt_title_color'		=> 'Цвет шрифта заголовка',
'themesetting_nt_title_color'		=> 'Цвет шрифта заголовка',
'theme_custom_tab_social_links'		=> 'Социальные линки',
'theme_custom_tab_social_links'		=> 'Социальные линки',
'themesetting_social_links_sidebar'		=> 'Позиция социальных линков: Фиксировать в боковой панели<span id="themesettings_desc">Вы можете добавить социальную ссылку, перейдя в</span><span id="themesettings_desc">ACP > System > Settings > <strong>General Configuration</strong></span>',
'themesetting_social_links_sidebar'		=> 'Позиция социальных линков: Фиксировать в боковой панели<span id="themesettings_desc">Вы можете добавить социальную ссылку, перейдя в</span><span id="themesettings_desc">ACP > System > Settings > <strong>General Configuration</strong></span>',
'themesetting_nav_fontcustom'		=> 'Шрифт навигации<span id="themesettings_desc">Введите<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>',
'themesetting_nav_fontcustom'		=> 'Шрифт навигации<span id="themesettings_desc">Введите<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>',
'themesetting_cat_id_r1'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'themesetting_cat_id_r1'		=> 'Категория<span id="themesettings_desc">Доступен множественный выбор</span>',
'themesetting_headerimage_height'		=> 'Изображение заголовка: Высота (в пикселях)<span id="themesettings_desc">Минимальная высота: 120. Максимальная высота: 500</span>',
'themesetting_headerimage_height'		=> 'Изображение заголовка: Высота (в пикселях)<span id="themesettings_desc">Минимальная высота: 120. Максимальная высота: 500</span>',
'themesetting_headerimage'		=> 'Заглавное изображение<span id="themesettings_desc">Это изображение используется на страницах, когда нет слайдера</span>',
'themesetting_headerimage'		=> 'Заглавное изображение<span id="themesettings_desc">Это изображение используется на страницах, когда нет слайдера</span>',
'themesetting_editor_toolbartabson'		=> 'Панель инструментов редактора Активные вкладки',
'themesetting_editor_toolbartabson'		=> 'Панель инструментов редактора Активные вкладки',
'themesetting_title_padding'		=> 'Заголовок, размер<span id="themesettings_desc">Размер, используемый для всех заголовков блоков и разделов сайта</span>',
'themesetting_title_padding'		=> 'Заголовок, размер<span id="themesettings_desc">Размер, используемый для всех заголовков блоков и разделов сайта</span>',
'themesetting_cat_private_g_r2'		=> 'Exclude from (2)',
'themesetting_cat_private_g_r2'		=> 'Exclude from (2)',
'themesetting_sl_style'		=> 'Стиль',
'themesetting_sl_style'		=> 'Стиль',
'themesetting_social_links_pos'		=> 'Позиция социальных линков<span id="themesettings_desc">Вы можете добавить социальную ссылку, перейдя в</span><span id="themesettings_desc">ACP > System > Settings > <strong>General Configuration</strong></span>',
'themesetting_social_links_pos'		=> 'Позиция социальных линков<span id="themesettings_desc">Вы можете добавить социальную ссылку, перейдя в</span><span id="themesettings_desc">ACP > System > Settings > <strong>General Configuration</strong></span>',
'themesetting_footer_text'		=> 'Авторское право: Ссылки',
'themesetting_footer_text'		=> 'Авторское право: Ссылки',
'themesetting_slider_3_title'		=> 'Заголовок',
'themesetting_slider_3_title'		=> 'Заголовок',
'themesetting_authorpanel_stripe'		=> 'Текстура панели автора<span id="themesettings_desc">Используется на панелях автора</span>',
'themesetting_authorpanel_stripe'		=> 'Текстура панели автора<span id="themesettings_desc">Используется на панелях автора</span>',
'themesetting_messages_success'		=> 'Уровень сообщения: Успех',
'themesetting_messages_success'		=> 'Уровень сообщения: Успех',
'themesetting_footer_about'		=> 'О нас',
'themesetting_footer_about'		=> 'О нас',
'themesetting_body_fontcustom'		=> 'Body Шрифт: Пользовательский<span id="themesettings_desc">введите<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>
<style type="text/css">
#themesettings_desc{display:block;font-size:11px;font-weight:normal;color:#000}#themesettings_desc_a{margin:0 5px}.ipsControlStrip_button{overflow:hidden;font-size:0}.ipsControlStrip_button #themesettings_desc,.ipsControlStrip_button #themesettings_desc_a,[id*=frontendcolors] ul > li#theme_setting_header{display:none !important}[id*=slider_reorder] .ipsField_autocomplete{max-width:50%}[id*=slider_reorder] .ipsField_autocomplete .cToken{border-radius:3px}[id*=frontendcolors] ul > li[id*=_dataitem_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=button] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=button_font] .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=input] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r1] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r1] .ipsFieldRow_title,[id*=global_widgets] ul > li[id*=_bottom] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=_widget_] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=sidebar_bg] .ipsFieldRow_title,[id*=_header_] ul > li[id*=main_nav_tab] .ipsFieldRow_title,[id*=_header_] ul > li#theme_setting_menu_borders .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_1] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=topic_] .ipsFieldRow_title{color:#F44336 !important}[id*=frontendcolors] ul > li[id*=_messages_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=tab]:not([id*=pagination_tabbg]) .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=checkbox] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r2] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r2] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_2] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=ipsquote] .ipsFieldRow_title{color:#9C27B0 !important}[id*=frontendcolors] ul > li[id*=_notification_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=pagination] .ipsFieldRow_title,[id*=global_widgets] ul > li[id*=_top] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=_section_] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_3] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=_editor_] .ipsFieldRow_title{color:#3F51B5 !important}[id*=frontendcolors] ul > li[id*=_moderated] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_repscore_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=area_]:not([id*=area_stripe]) .ipsFieldRow_title,[id*=bodytab] ul > li[id*=wrapper_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=ipsbox_bg] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_4] .ipsFieldRow_title,[id*=_header_] ul > li[id*=menu_hover_] .ipsFieldRow_title{color:#009688 !important}[id*=frontendcolors] ul > li[id*=_trophy_] .ipsFieldRow_title{color:#795548 !important}[id*=frontendcolors] ul > li[id*=dialog] .ipsFieldRow_title{color:#0DC36A !important}[id*=frontendcolors] ul > li[id*=_rating_] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_status_] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_item_status] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_userbar] .ipsFieldRow_title{color:#B31414 !important}[id*=frontendcolors] ul > li[id*=_comment_] .ipsFieldRow_title{color:#0DB2C7 !important}[id*=frontendcolors] ul > li[id*=_mobile_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=body_bg] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=page_] .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=select] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r3] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r3] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_search_] .ipsFieldRow_title{color:#2196F3 !important}[id*=frontendcolors] ul > li[id*=_highlight] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=comment_popular] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_site_] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_headerimage] .ipsFieldRow_title,
[id*=_header_] ul > li[id=theme_setting_header] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_5] .ipsFieldRow_title{color:#FF9800 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (1)"]{background:#F44336 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (2)"]{background:#9C27B0 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (3)"]{background:#3F51B5 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (4)"]{background:#009688 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (5)"]{background:#FF9800 !important}
[id*=sidebars_widgets] ul > li[id*=title_padding] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=title_fontsize] .ipsFieldRow_title{color:#009688 !important}
.ipsTabs li> [id*=theme_custom_tab_colorizer]{background: #d66723!important;color: #fff!important;font-weight: 600;}
</style>',
'themesetting_body_fontcustom'		=> 'Body Шрифт: Пользовательский<span id="themesettings_desc">введите<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>
<style type="text/css">
#themesettings_desc{display:block;font-size:11px;font-weight:normal;color:#000}#themesettings_desc_a{margin:0 5px}.ipsControlStrip_button{overflow:hidden;font-size:0}.ipsControlStrip_button #themesettings_desc,.ipsControlStrip_button #themesettings_desc_a,[id*=frontendcolors] ul > li#theme_setting_header{display:none !important}[id*=slider_reorder] .ipsField_autocomplete{max-width:50%}[id*=slider_reorder] .ipsField_autocomplete .cToken{border-radius:3px}[id*=frontendcolors] ul > li[id*=_dataitem_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=button] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=button_font] .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=input] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r1] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r1] .ipsFieldRow_title,[id*=global_widgets] ul > li[id*=_bottom] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=_widget_] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=sidebar_bg] .ipsFieldRow_title,[id*=_header_] ul > li[id*=main_nav_tab] .ipsFieldRow_title,[id*=_header_] ul > li#theme_setting_menu_borders .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_1] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=topic_] .ipsFieldRow_title{color:#F44336 !important}[id*=frontendcolors] ul > li[id*=_messages_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=tab]:not([id*=pagination_tabbg]) .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=checkbox] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r2] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r2] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_2] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=ipsquote] .ipsFieldRow_title{color:#9C27B0 !important}[id*=frontendcolors] ul > li[id*=_notification_] .ipsFieldRow_title,[id*=buttoncolors] ul > li[id*=pagination] .ipsFieldRow_title,[id*=global_widgets] ul > li[id*=_top] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=_section_] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_3] .ipsFieldRow_title,[id*=topic_view] ul > li[id*=_editor_] .ipsFieldRow_title{color:#3F51B5 !important}[id*=frontendcolors] ul > li[id*=_moderated] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_repscore_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=area_]:not([id*=area_stripe]) .ipsFieldRow_title,[id*=bodytab] ul > li[id*=wrapper_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=ipsbox_bg] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_4] .ipsFieldRow_title,[id*=_header_] ul > li[id*=menu_hover_] .ipsFieldRow_title{color:#009688 !important}[id*=frontendcolors] ul > li[id*=_trophy_] .ipsFieldRow_title{color:#795548 !important}[id*=frontendcolors] ul > li[id*=dialog] .ipsFieldRow_title{color:#0DC36A !important}[id*=frontendcolors] ul > li[id*=_rating_] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_status_] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=_item_status] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_userbar] .ipsFieldRow_title{color:#B31414 !important}[id*=frontendcolors] ul > li[id*=_comment_] .ipsFieldRow_title{color:#0DB2C7 !important}[id*=frontendcolors] ul > li[id*=_mobile_] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=body_bg] .ipsFieldRow_title,[id*=bodytab] ul > li[id*=page_] .ipsFieldRow_title,[id*=forms_toggles] ul > li[id*=select] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=_r3] .ipsFieldRow_title,[id*=forum_categories] ul > li[id*=category_r3] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_search_] .ipsFieldRow_title{color:#2196F3 !important}[id*=frontendcolors] ul > li[id*=_highlight] .ipsFieldRow_title,[id*=frontendcolors] ul > li[id*=comment_popular] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_site_] .ipsFieldRow_title,[id*=_header_] ul > li[id*=_headerimage] .ipsFieldRow_title,
[id*=_header_] ul > li[id=theme_setting_header] .ipsFieldRow_title,[id*=_sliders_] ul > li[id*=slider_5] .ipsFieldRow_title{color:#FF9800 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (1)"]{background:#F44336 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (2)"]{background:#9C27B0 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (3)"]{background:#3F51B5 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (4)"]{background:#009688 !important}[id*=slider_reorder] .ipsField_autocomplete .cToken[data-value="Slider (5)"]{background:#FF9800 !important}
[id*=sidebars_widgets] ul > li[id*=title_padding] .ipsFieldRow_title,[id*=sidebars_widgets] ul > li[id*=title_fontsize] .ipsFieldRow_title{color:#009688 !important}
.ipsTabs li> [id*=theme_custom_tab_colorizer]{background: #d66723!important;color: #fff!important;font-weight: 600;}
</style>',
'themesetting_site_titlefont'		=> 'Логотип заголовка: Цвет',
'themesetting_site_titlefont'		=> 'Логотип заголовка: Цвет',
'themesetting_slider_5_wcs'		=> 'Кому доступно?',
'themesetting_slider_5_wcs'		=> 'Кому доступно?',
'theme_custom_tab_sidebars_widgets'		=> 'Блоки и заголовки',
'theme_custom_tab_sidebars_widgets'		=> 'Блоки и заголовки',
'theme_custom_tab_categories_sidebars'		=> 'Стиль форумов',
'theme_custom_tab_categories_sidebars'		=> 'Стиль форумов',
'themesetting_messages_error'		=> 'Уровень сообщения: ошибка',
'themesetting_messages_error'		=> 'Уровень сообщения: ошибка',
'themesetting_site_title_shadows'		=> 'Логотип заголовка: тени<span id="themesettings_desc">Некоторые текстовые генераторы тени <a href="https://css3gen.com/text-shadow/" target="_blank" id="themesettings_desc_a"> css3gen </a><a href="http://www.css3generator.in/text-shadow.html" target="_blank" id="themesettings_desc_a"> css3generator </a></span>',
'themesetting_site_title_shadows'		=> 'Логотип заголовка: тени<span id="themesettings_desc">Некоторые текстовые генераторы тени <a href="https://css3gen.com/text-shadow/" target="_blank" id="themesettings_desc_a"> css3gen </a><a href="http://www.css3generator.in/text-shadow.html" target="_blank" id="themesettings_desc_a"> css3generator </a></span>',
'themesetting_item_status_notactive'		=> 'Значки состояния товара НЕ активны',
'themesetting_item_status_notactive'		=> 'Значки состояния товара НЕ активны',
'themesetting_slider_reorder'		=> 'Сортировать слайдеры',
'themesetting_slider_reorder'		=> 'Сортировать слайдеры',
'themesetting_sl_iconhovercolor'		=> 'Фон: цвет наведения',
'themesetting_sl_iconhovercolor'		=> 'Фон: цвет наведения',
'themesetting_cat_private_ti_font_r2'		=> 'Цвет заголовка (2)',
'themesetting_cat_private_ti_font_r2'		=> 'Цвет заголовка (2)',
'themesetting_footer_showonmobile'		=> 'Показать на мобильных телефонах и планшетах?',
'themesetting_footer_showonmobile'		=> 'Показать на мобильных телефонах и планшетах?',
'themesetting_ipsquotecode_bg'		=> 'Цитата / Фон кода',
'themesetting_ipsquotecode_bg'		=> 'Цитата / Фон кода',
'themesetting_slider_3_wcs'		=> 'Кому доступно?',
'themesetting_slider_3_wcs'		=> 'Кому доступно?',
'themesetting_input_focusbg'		=> 'Input: Focus background',
'themesetting_input_focusbg'		=> 'Input: Focus background',
'themesetting_messages_info'		=> 'Фон сообщения: Информация',
'themesetting_messages_info'		=> 'Фон сообщения: Информация',
'themesetting_pagination_active'		=> 'Pagination: Активный фон',
'themesetting_pagination_active'		=> 'Pagination: Активный фон',
'themesetting_ipsdialog_title'		=> 'Всплывающее окно: Название',
'themesetting_ipsdialog_title'		=> 'Всплывающее окно: Название',
'themesetting_g_widget_position_bottom'		=> 'Кому доступно?',
'themesetting_g_widget_position_bottom'		=> 'Кому доступно?',
'themesetting_messages_font'		=> 'Сообщения: цвет текста',
'themesetting_messages_font'		=> 'Сообщения: цвет текста',
'themesetting_input_focusborder'		=> 'Input: Focus border',
'themesetting_input_focusborder'		=> 'Input: Focus border',
'themesetting_ipsmenu_title_color'		=> 'ipsMenu: Цвет шрифта заголовка',
'themesetting_ipsmenu_title_color'		=> 'ipsMenu: Цвет шрифта заголовка',
'themesetting_slider_4'		=> 'Слайдер (4)',
'themesetting_slider_4'		=> 'Слайдер (4)',
'themesetting_authorpanel_texture'		=> 'Текстура панели автора<span id="themesettings_desc">Используется на панелях автора</span>',
'themesetting_authorpanel_texture'		=> 'Текстура панели автора<span id="themesettings_desc">Используется на панелях автора</span>',
'themesetting_dataitem_error'		=> 'Фон элемента данных: ошибка',
'themesetting_dataitem_error'		=> 'Фон элемента данных: ошибка',
'themesetting_notification_unreadfont'		=> 'Уведомление: новый шрифт статус',
'themesetting_notification_unreadfont'		=> 'Уведомление: новый шрифт статус',
'themesetting_nt_title'		=> 'Заголовок',
'themesetting_nt_title'		=> 'Заголовок',
'themesetting_footer_articles'		=> 'Страницы Статей',
'themesetting_footer_articles'		=> 'Страницы Статей',
'themesetting_dataitem_info'		=> 'Фон элемента данных: информация',
'themesetting_dataitem_info'		=> 'Фон элемента данных: информация',
'themesetting_social_links_hide'		=> 'Скрыть в верхнем и нижнем колонтитулах',
'themesetting_social_links_hide'		=> 'Скрыть в верхнем и нижнем колонтитулах',
'themesetting_cat_ti_bg_r1'		=> 'Категория Фон заголовка (1)',
'themesetting_cat_ti_bg_r1'		=> 'Категория Фон заголовка (1)',
'themesetting_tabs_buttonbg'		=> 'Вкладки: фон кнопки',
'themesetting_tabs_buttonbg'		=> 'Вкладки: фон кнопки',
'themesetting_u_hdrimgs'		=> 'Изображение заголовка: использование с ползунков',
'themesetting_u_hdrimgs'		=> 'Изображение заголовка: использование с ползунков',
'themesetting_slider_enable_articles'		=> 'Страницы статей',
'themesetting_slider_enable_articles'		=> 'Страницы статей',
'themesetting_nt_custom_content'		=> 'Пользовательские тикеры<span id="themesettings_desc">Ticker must be in an <strong>li</strong> tag</span>',
'themesetting_nt_custom_content'		=> 'Пользовательские тикеры<span id="themesettings_desc">Ticker must be in an <strong>li</strong> tag</span>',
'themesetting_remove_page_headers'		=> 'Удалить заголовки страниц',
'themesetting_remove_page_headers'		=> 'Удалить заголовки страниц',
'themesetting_slider_article_icon'		=> 'Статьи. Цвет значков',
'themesetting_slider_article_icon'		=> 'Статьи. Цвет значков',
'themesetting_slider_2_wcs'		=> 'Кому доступно?',
'themesetting_slider_2_wcs'		=> 'Кому доступно?',
'themesetting_search_bordercolors'		=> 'Поиск. Цвет рамки',
'themesetting_search_bordercolors'		=> 'Поиск. Цвет рамки',
'themesetting_nt_tickers'		=> 'Tickers',
'themesetting_nt_tickers'		=> 'Tickers',
'themesetting_dataitem_new_success'		=> 'Фон элемента данных: новый и ожидаемый',
'themesetting_dataitem_new_success'		=> 'Фон элемента данных: новый и ожидаемый',
'themesetting_nt_speed'		=> 'Скорость',
'themesetting_nt_speed'		=> 'Скорость',
'themesetting_sidebar_width'		=> 'Ширина боковой панели (в пикселях)',
'themesetting_sidebar_width'		=> 'Ширина боковой панели (в пикселях)',
'themesetting_main_nav_desktop'		=> 'Обои для рабочего Nav Nav',
'themesetting_main_nav_desktop'		=> 'Обои для рабочего Nav Nav',
'themesetting_pagination_actifont'		=> 'Pagination: активный текст',
'themesetting_pagination_actifont'		=> 'Pagination: активный текст',
'themesetting_g_widget_content_top'		=> 'Наполнение',
'themesetting_g_widget_content_top'		=> 'Наполнение',
'themesetting_dataitem_status'		=> 'Фон элемента данных: Статус',
'themesetting_dataitem_status'		=> 'Фон элемента данных: Статус',
'themesetting_header_remob'		=> 'Заглавное изображение: удалить на мобильном устройстве',
'themesetting_header_remob'		=> 'Заглавное изображение: удалить на мобильном устройстве',
'themesetting_cat_private_bg_r2'		=> 'Обложка (2)<span id="themesettings_desc">%70 Прозрачный</span>',
'themesetting_cat_private_bg_r2'		=> 'Обложка (2)<span id="themesettings_desc">%70 Прозрачный</span>',
'themesetting_input_bordercolor'		=> 'Вход: цвет границы',
'themesetting_input_bordercolor'		=> 'Вход: цвет границы',
'themesetting_cat_private_ti_r1'		=> 'Название обложки (1)',
'themesetting_cat_private_ti_r1'		=> 'Название обложки (1)',
'themesetting_messages_warning'		=> 'Фон сообщения: Внимание',
'themesetting_messages_warning'		=> 'Фон сообщения: Внимание',
'theme_custom_tab_stripes'		=> 'Текстуры',
'theme_custom_tab_stripes'		=> 'Текстуры',
'themesetting_social_locationt'		=> 'Показать в верхней части',
'themesetting_social_locationt'		=> 'Показать в верхней части',
'themesetting_body_bg_position'		=> 'Body: Фоновая позиция<span id="themesettings_desc">Это поле задает начальную позицию фонового изображения тела. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>left top, left center, left bottom, right top, right center, right bottom, center top, center center, center bottom</strong></em></span>',
'themesetting_body_bg_position'		=> 'Body: Фоновая позиция<span id="themesettings_desc">Это поле задает начальную позицию фонового изображения тела. Вы можете использовать одно из ключевых слов или значений в процентах и ​​пикселях.</span><span id="themesettings_desc"><em><strong>left top, left center, left bottom, right top, right center, right bottom, center top, center center, center bottom</strong></em></span>',
'themesetting_dataitem_warning'		=> 'Фон элемента данных: Внимание (предупреждение)',
'themesetting_dataitem_warning'		=> 'Фон элемента данных: Внимание (предупреждение)',
'theme_custom_tab_header'		=> 'Заголовок и Навигация',
'theme_custom_tab_header'		=> 'Заголовок и Навигация',
'themesetting_editor_toolbarbg'		=> 'Фон панели инструментов редактора',
'themesetting_editor_toolbarbg'		=> 'Фон панели инструментов редактора',
'themesetting_cat_private_r3'		=> 'Применить обложку (3)',
'themesetting_cat_private_r3'		=> 'Применить обложку (3)',
'themesetting_body_bg_attachment'		=> 'Сайт: вложение фонового изображения',
'themesetting_body_bg_attachment'		=> 'Сайт: вложение фонового изображения',
'themesetting_header_borderseparator'		=> 'Header Frames<span id="themesettings_desc"></span>',
'themesetting_header_borderseparator'		=> 'Header Frames<span id="themesettings_desc"></span>',
'themesetting_sl_iconcolor'		=> 'Цвет иконок',
'themesetting_sl_iconcolor'		=> 'Цвет иконок',
'themesetting_ipsmenu_title_bg'		=> 'ipsMenu: Фон заголовка',
'themesetting_ipsmenu_title_bg'		=> 'ipsMenu: Фон заголовка',
'themesetting_title_stripe'		=> 'Title texture<span id="themesettings_desc">Используется во всех титрах</span>',
'themesetting_title_stripe'		=> 'Title texture<span id="themesettings_desc">Используется во всех титрах</span>',
'themesetting_repscore_neutralbg'		=> 'Профиль: Фон нейтральной репутации',
'themesetting_repscore_neutralbg'		=> 'Профиль: Фон нейтральной репутации',
'themesetting_topic_unread_border'		=> 'Тема Непрочитанная граница разделителя',
'themesetting_topic_unread_border'		=> 'Тема Непрочитанная граница разделителя',
'themesetting_slider_1_img'		=> 'Фото слайдера',
'themesetting_slider_1_img'		=> 'Фото слайдера',
'themesetting_cat_private_bg_r1'		=> 'Обложка (1)<span id="themesettings_desc">%70 прозрачный</span>',
'themesetting_cat_private_bg_r1'		=> 'Обложка (1)<span id="themesettings_desc">%70 прозрачный</span>',
'themesetting_slider_1_buttons'		=> 'Кнопка на слайдере',
'themesetting_slider_1_buttons'		=> 'Кнопка на слайдере',
'themesetting_sl_background'		=> 'Задний план',
'themesetting_sl_background'		=> 'Задний план',
'themesetting_category_r3'		=> 'Стиль категорий форума (3)',
'themesetting_category_r3'		=> 'Стиль категорий форума (3)',
'themesetting_cat_private_ti_r2'		=> 'Название обложки (2)',
'themesetting_cat_private_ti_r2'		=> 'Название обложки (2)',
'themesetting_dataitem_zebra'		=> 'Фон элемента данных: Zebra',
'themesetting_dataitem_zebra'		=> 'Фон элемента данных: Zebra',
'themesetting_search_background'		=> 'Фон поиска',
'themesetting_search_background'		=> 'Фон поиска',
'themesetting_checkbox_border'		=> 'Checkbox: Граница',
'themesetting_checkbox_border'		=> 'Checkbox: Граница',
'themesetting_slider_enable_overlay'		=> 'Включить шаблон наложения',
'themesetting_slider_enable_overlay'		=> 'Включить шаблон наложения',
'themesetting_notification_unreadbg'		=> 'Уведомление: новый статус фона',
'themesetting_notification_unreadbg'		=> 'Уведомление: новый статус фона',
'themesetting_widget_titbar_custcss'		=> 'Виджет заголовка Пользовательский CSS',
'themesetting_widget_titbar_custcss'		=> 'Виджет заголовка Пользовательский CSS',
'themesetting_pagination_fontcolor'		=> 'Pagination: Text',
'themesetting_pagination_fontcolor'		=> 'Pagination: Text',
'theme_custom_tab_swiper_slider'		=> 'Swiper Slider',
'theme_custom_tab_swiper_slider'		=> 'Swiper Slider',
);
