<ips:template parameters="$forum" />
{{if $forum->can('view')}}
{{$lastPost = $forum->lastPost();}}
	<div class="ipsDataItem ipsGrid_span4 ipsAreaBackground_reset cForumGrid {{if \IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}cForumGrid_unread ipsDataItem_unread{{endif}} ipsClearfix" data-forumID="{$forum->_id}">

		<div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix ipsPad cForumGrid_forumInfo'>
			<span class='ipsPos_left'>
				{{if !$forum->redirect_on AND \IPS\forums\Topic::containerUnread( $forum ) AND \IPS\Member::loggedIn()->member_id}}
					<a href="{$forum->url()->setQueryString( 'do', 'markRead' )->csrf()}" data-action='markAsRead'>
				{{endif}}
					{{if $forum->icon}}
						<img src="{file="$forum->icon" extension="forums_Icons"}" class='ipsItemStatus ipsItemStatus_custom {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}'>
					{{else}}
						{{if $forum->redirect_on}}
							<span class='ipsItemStatus ipsItemStatus_large cForumIcon_redirect {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
								{{foreach explode(',',theme.volpe_fn_redirect_icon) as $key => $icon}}
									<i class='fa fa-{$icon}'></i>
								{{endforeach}}
							</span>
						{{elseif $forum->forums_bitoptions['bw_enable_answers']}}
							<span class='ipsItemStatus ipsItemStatus_large cForumIcon_answers {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
								{{foreach explode(',',theme.volpe_fn_question_icon) as $key => $icon}}
									<i class='fa fa-{$icon}'></i>
								{{endforeach}}
							</span>
						{{elseif $forum->password}}
							<span class='ipsItemStatus ipsItemStatus_large cForumIcon_password {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
								{{if $forum->loggedInMemberHasPasswordAccess()}}
									{{foreach explode(',',theme.volpe_fn_unlock_icon) as $key => $icon}}
										<i class='fa fa-{$icon}'></i>
									{{endforeach}}
								{{else}}
									{{foreach explode(',',theme.volpe_fn_lock_icon) as $key => $icon}}
										<i class='fa fa-{$icon}'></i>
									{{endforeach}}
								{{endif}}
							</span>
						{{else}}
							<span class='ipsItemStatus ipsItemStatus_large cForumIcon_normal {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
								{{foreach explode(',',theme.volpe_fn_discussion_icon) as $key => $icon}}
									<i class='fa fa-{$icon}'></i>
								{{endforeach}}
							</span>
						{{endif}}
					{{endif}}
				{{if !$forum->redirect_on AND \IPS\forums\Topic::containerUnread( $forum ) AND \IPS\Member::loggedIn()->member_id}}
					</a>
				{{endif}}
			</span>
			<div>
				<h3 class='ipsType_reset ipsType_sectionHead ipsTruncate ipsTruncate_line cForumGrid_title'>
					{{if $forum->password && !$forum->loggedInMemberHasPasswordAccess()}}
						<a href="{$forum->url()->setQueryString( 'passForm', '1' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="forum_requires_password" sprintf="$forum->_title"}'>{$forum->_title}</a>
					{{else}}
						<a href="{$forum->url()}">{$forum->_title}</a>
					{{endif}}
				</h3>
				{{if !$forum->redirect_on}}
					{{$count = \IPS\forums\Topic::contentCount( $forum, TRUE );}}
					{{if $forum->hasChildren()}}{{$cSubTopics = 0;}}{{foreach $forum->children() as $subforum}}{{$cSubTopics += $subforum->topics;}}{{endforeach}}{{$cTopics = $forum->topics + $cSubTopics;}}{{else}}{{$cTopics = $forum->topics;}}{{endif}}
					{{if theme.volpe_forumrow_show_posts or theme.volpe_forumrow_show_topics}}
					<p class='ipsType_reset ipsType_light'>{{if theme.volpe_forumrow_show_topics}}{lang="topics_number" pluralize="$cTopics"} {{endif}}{{if theme.volpe_forumrow_show_posts}}{lang="posts_number" pluralize="$count"}{{endif}}</p>
					{{endif}}
				{{endif}}
				{{if \IPS\forums\Topic::modPermission( 'unhide', NULL, $forum ) AND ( $forum->queued_topics OR $forum->queued_posts )}}
					<strong class='ipsType_warning ipsType_medium'>
						<i class='fa fa-warning'></i>
						{{if $forum->queued_topics}}
							<a href='{$forum->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_topics' ) )->csrf()}' data-ipsTooltip title='{lang="queued_topics_badge" pluralize="$forum->queued_topics"}' class='ipsType_blendLinks'>{$forum->queued_topics}</a>
						{{else}}
							<span class='ipsType_light'>0</span>
						{{endif}}
						/
						{{if $forum->queued_posts}}
							<a href='{$forum->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_posts' ) )->csrf()}' data-ipsTooltip title='{lang="queued_posts_badge" pluralize="$forum->queued_posts"}' class='ipsType_blendLinks'>{$forum->queued_posts}</a>
						{{else}}
							<span class='ipsType_light'>0</span>
						{{endif}}
					</strong>					
				{{endif}}
			</div>
		</div>
		
		<div class='ipsPad'>
			{{if $forum->description}}
				<div class='ipsType_richText ipsType_medium'>{$forum->description|raw}</div>
			{{endif}}

			{{if $forum->hasChildren()}}
				<h4 class='ipsType_minorHeading ipsSpacer_top'>{lang="subforums"}</h4>
				<ul class="ipsList_inline">
					{{foreach $forum->children() as $subforum}}
					<li class="{{if \IPS\forums\Topic::containerUnread( $subforum )}}ipsDataItem_unread{{endif}}">
						<a href="{$subforum->url()}">
							{{if \IPS\forums\Topic::containerUnread( $subforum )}}
								<span class='ipsItemStatus ipsItemStatus_tiny {{if !\IPS\forums\Topic::containerUnread( $subforum ) && !$subforum->redirect_on}}ipsItemStatus_read{{endif}}'>
									<i class="fa fa-circle"></i>
								</span>
							{{endif}}
							{$subforum->_title}
						</a>
					</li>
					{{endforeach}}
				</ul>
			{{endif}}
		</div>

		<div class='cForumGrid_info'>
			<hr class='ipsHr'>

			{{if !$forum->redirect_on}}
				{{if $lastPost}}
					<div class='ipsPhotoPanel ipsPhotoPanel_tiny'>
						{template="userPhoto" app="core" group="global" params="$lastPost['author'], 'tiny'"}
						<div>
							<ul class='ipsList_reset'>
								<li><a href="{$lastPost['topic_url']->setQueryString( 'do', 'getNewComment' )}" class='ipsType_break' title='{$lastPost['topic_title']}'>{truncate="$lastPost['topic_title']" length="30"}</a></li>
								<li class='ipsType_light ipsTruncate ipsTruncate_line'>{lang="byline_nodate" htmlsprintf="$lastPost['author']->link()"}, <a href='{$lastPost['topic_url']->setQueryString( 'do', 'getLastComment' )}' title='{lang="get_last_post"}' class='ipsType_blendLinks'>{datetime="$lastPost['date']"}</a></li>
							</ul>
						</div>
					</div>
				{{else}}
					<p class='ipsType_light ipsType_reset ipsTruncate ipsTruncate_line'>{{if $forum->password}}{lang="no_forum_posts_password"}{{else}}{lang="no_forum_posts"}{{endif}}</p>
				{{endif}}
			{{else}}
				<p class='ipsType_light ipsType_reset ipsTruncate ipsTruncate_line'>
					{lang="redirect_hits" pluralize="$forum->redirect_hits"}
				</p>
			{{endif}}
		</div>
	</div>
{{endif}}