<ips:template parameters="$downloadUrl" />
<div class="ipsPad">
	{lang="md5_fail_download_1"}
	<div class="ipsType_center ipsSpacer_bottom">
		<a href="{$downloadUrl}" class="ipsButton ipsButton_important ipsButton_large"><i class="fa fa-cloud-download"></i> {lang="md5_fail_download"}</a>
	</div>
	{lang="md5_fail_download_2"}
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a href="{url="app=core&module=support&controller=support"}" class="ipsButton ipsButton_alternate">{lang="support_check_again"}</a>
</div>
