<ips:template parameters="$form, $login" />

<section class='ipsBox_alt ipsPad'>
	<br>
	<h1 class='ipsType_veryLarge ipsType_center ipsType_reset'>{lang='sign_up'}</h1>
	<p class='ipsType_reset ipsType_large ipsType_center ipsType_light'>{lang="existing_user"} <a href='{url="app=core&module=system&controller=login" seoTemplate="login"}'>{lang="sign_in_short"}</a></p>
	<br>

	<div data-role='registerForm'>
		<div class='ipsColumns ipsColumns_collapseTablet'>
			{{$buttonMethods = $login->buttonMethods();}}
			{{if $buttonMethods}}
				<div class='ipsColumn ipsColumn_fluid'>
			{{endif}}
					<div class='ipsBox ipsPad_double {{if !$buttonMethods}}cRegister_noSocial ipsPos_center{{endif}}'>
						{$form|raw}
					</div>
			{{if $buttonMethods}}
				</div>
				<div class='ipsColumn ipsColumn_wide' id='elRegisterSocial'>
					<div class='ipsBox ipsPad'>
						<h2 class='ipsType_sectionHead'>{lang='reg_start_faster'}</h2>
						<p class='ipsType_normal ipsType_reset ipsType_light'>{lang='reg_connect'}</p>
						<br>
						<form accept-charset='utf-8' method='post' action='{$login->url}' data-controller="core.global.core.login">
							<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
							{{foreach $buttonMethods as $method}}
								<div class='ipsType_center ipsPad_half'>
									{$method->button()|raw}
								</div>
							{{endforeach}}
						</form>
					</div>
				</div>
			{{endif}}
		</div>
	</div>
</section>