<ips:template parameters="$blockHtml, $info, $collapsed=array()" />

<li data-widgetKey='{$info['key']}' data-widgetName='{$info['name']}'>
	<div class='ipsBox acpWidget_item'>
		<h2 class='ipsBox_titleBar ipsType_reset ipsCursor_pointer' data-widgetCollapse>
			<ul class='ipsList_reset ipsList_inline acpWidget_tools'>
				<li>
					<noscript>
						<input type='text' value='{{if isset($info['position'])}}{$info['position']}{{else}}0{{endif}}' class='acpWidget_manualReorder'>
					</noscript>
					<a href='#' class='acpWidget_reorder ipsJS_show ipsCursor_drag' data-ipsTooltip title='{lang="reorder_widget"}'><i class='fa fa-bars'></i></a>
				</li>
				<li>
					<a href='#' class='acpWidget_close' data-ipsTooltip title='{lang="close_widget"}'><i class='fa fa-times'></i></a>
				</li>
			</ul>
			<i class='fa fa-{{if in_array( $info['key'], $collapsed )}}caret-right{{else}}caret-down{{endif}}'></i> {lang="block_{$info['key']}"}
		</h2>
		<div data-role="widgetContent" data-widgetCollapsed='{{if in_array( $info['key'], $collapsed )}}true{{else}}false{{endif}}' data-widgetCollapse-content class='ipsPad'>
			{$blockHtml|raw}
		</div>
	</div>
</li>