<ips:template parameters="$title,$html,$location=array()" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<meta charset="utf-8">
		<title>{$title}</title>
		<!--[if lt IE 9]>
		    <script src="{url="applications/core/interface/html5shiv/html5shiv.js" base="none" protocol="\IPS\Http\Url::PROTOCOL_RELATIVE"}"></script>
		<![endif]-->
		{template="includeCSS" app="core" group="global" location="global" params=""}
		{template="includeJS" app="core" group="global" location="global" params=""}
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="referrer" content="origin-when-cross-origin">
	</head>
	<body data-baseurl="{setting="base_url"}" class='ipsApp ipsApp_admin {{if isset( \IPS\Request::i()->cookie['hasJS'] )}}ipsJS_has{{else}}ipsJS_none{{endif}} {{if isset( \IPS\Request::i()->cookie['hideAdminMenu'] )}}cAdminHideMenu{{endif}} {{foreach output.bodyClasses as $class}} {$class}{{endforeach}}' data-controller="{expression="implode( ',', \IPS\Output::i()->globalControllers )"}" {{if isset( output.inlineMessage )}}data-message="{expression="output.inlineMessage"}"{{endif}} data-pageApp='{$location['app']}' data-pageLocation='admin' data-pageModule='{$location['module']}' data-pageController='{$location['controller']}'>
		<a href='#content' id='acpJumpToContent'>{lang="jump_to_content"}</a>
		<a id='content'></a>
		<div id='ipsLayout_header' class='ipsClearfix' role='banner' data-controller='core.admin.core.mobileNav'>
			{{if member.hasAcpRestriction( 'core', 'livesearch', 'livesearch_manage')}}
				<i class='fa fa-search'></i> <input type='text' class='' id='acpSearchKeyword' placeholder='{lang="search_admincp"}'>
			{{endif}}
			<ul id='elAdminControls' class='ipsList_reset'>
				<li class='ipsResponsive_showDesktop ipsResponsive_block'>
					<a href='{expression="\IPS\Http\Url::baseUrl()"}' target='_blank'>
						<i class='fa fa-home'></i> {lang="site"}
					</a>
				</li>
				<li class='ipsResponsive_showDesktop ipsResponsive_block'>
					<a href='{url="app=core&module=support&controller=support"}'>
						<i class='fa fa-question-circle'></i> {lang="support"}
					</a>
				</li>
				<li id='elAdminUser' class='ipsCursor_pointer ipsResponsive_showDesktop ipsResponsive_block' data-ipsMenu>
					<img src='{member="photo"}' class='ipsUserPhoto ipsUserPhoto_tiny'>
					<i class='fa fa-angle-down'></i>
				</li>
				<li id='elAdminNav' class='ipsResponsive_hideDesktop' data-ipsDrawer data-ipsDrawer-drawerelem="#elMobileDrawer" title="{lang="admincp_menu"}">
					<a href="#"><i class="fa fa-bars"></i></a>
				</li>
			</ul>
		</div>
		<main class='ipsColumns ipsColumns_noSpacing' id='acpMainLayout'>
			<nav class='ipsColumn ipsColumn_veryWide ipsResponsive_hidePhone' id='acpAppMenu'>
				{{if isset( \IPS\Output::i()->sidebar['appmenu'] )}}{expression="\IPS\Output::i()->sidebar['appmenu']" raw="true"}{{endif}}
			</nav>
			<div class='ipsColumn ipsColumn_fluid' id='acpMainArea'>
				{template="renewalWarning" app="core" group="global" params=""}
				{template="lkeyWarning" app="core" group="global" location="global" params=""}
				{{if !in_array( 'acpHeader', \IPS\Output::i()->hiddenElements)}}
					{{if isset( \IPS\Output::i()->customHeader )}}
						{expression="\IPS\Output::i()->customHeader" raw="true"}
					{{else}}
						<div id='acpPageHeader'>
							{template="breadcrumb" app="core" location="admin" group="global"}
							
							<div class='acpPageHeader_flex'>
								{{if \IPS\Output::i()->showTitle}}
									<h1 class='ipsType_pageTitle ipsType_break'>
										{$title}
										{{if \IPS\Output::i()->editUrl}}
											<a href="{expression="\IPS\Output::i()->editUrl"}" class="ipsType_medium" data-ipsDialog data-ipsDialog-title="{lang="edit"}"><i class="fa fa-pencil"></i></a>
										{{endif}}
										{{if \IPS\IN_DEV}}
											{template="searchKeywords" group="global" app="core" params="'app=' . \IPS\Request::i()->app . '&module=' . \IPS\Request::i()->module . '&controller=' . \IPS\Request::i()->controller . ( ( isset( \IPS\Request::i()->do ) and \IPS\Request::i()->do != 'do' ) ? ( '&do=' . \IPS\Request::i()->do ) : '' ) . ( ( \IPS\Request::i()->controller == 'enhancements' and ( isset( \IPS\Request::i()->id ) ) ) ? ( '&id=' . \IPS\Request::i()->id ) : '' )"}
										{{endif}}
									</h1>
								{{endif}}

								{{if isset(\IPS\Output::i()->sidebar['actions'])}}
									<div class='acpToolbar ipsClearfix'>
										{template="pageButtons" app="core" group="global" location="admin" params="\IPS\Output::i()->sidebar['actions']"}
									</div>
								{{endif}}
							</div>
						</div>
					{{endif}}
				{{endif}}
				<div id='acpContent'>
					{{if \IPS\Output::i()->inlineMessage}}
						<noscript>
							<div class="ipsMessage ipsMessage_information ipsMessageInABottle">
								{expression="\IPS\Output::i()->inlineMessage"}
							</div>
						</noscript>
					{{endif}}

					{{if !\IPS\Output::i()->responsive}}
						<div class='ipsResponsive_showPhone ipsResponsive_block ipsType_center'>
							<i class='ipsType_huge fa fa-tablet'></i><br>
							<h2 class='ipsType_sectionHead'>{lang="not_mobile"}</h2>
							<br><br>
							<p class='ipsType_normal'>
								{lang="not_mobile_desc"}
							</p>
						</div>
						<div class='ipsResponsive_hidePhone'>
							{$html|raw}
						</div>
					{{else}}
						{$html|raw}
					{{endif}}
				</div>
			</div>
		</main>
		
		<div id='acpLiveSearchResults' class='ipsHide' data-controller='core.admin.core.liveSearch'>
			<div class='cAcpSearch'>
				<div class='cAcpSearch_areas' data-role="searchMenu">
					<div data-ipsSideMenu data-ipsSideMenu-type='radio'>
						<ul class="ipsSideMenu_list">
							{{foreach \IPS\Application::allExtensions( 'core', 'LiveSearch', TRUE, 'core', 'Settings' ) as $key => $extension}}
								{{if $extension->hasAccess()}}
									<li class="ipsSideMenu_item ipsSideMenu_itemDisabled" data-ipsMenuValue='{$key}' {{if method_exists( $extension, 'isDefault' ) and $extension->isDefault()}}data-role="defaultTab"{{endif}}><a href="#">{lang="acp_search_title_{$key}"} <span data-role="resultCount" class='ipsSideMenu_itemCount ipsLoading ipsLoading_tiny ipsPad_top'>&nbsp;&nbsp;</span></a></li>
								{{endif}}
							{{endforeach}}
						</ul>
					</div>
				</div>
				<div class='cAcpSearch_results ipsPad ipsScrollbar' data-role="searchResults"></div>
			</div>
		</div>
		<ul id='elAdminUser_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
			<li class='ipsMenu_item'><a href='{url="app=core&module=overview&controller=dashboard&do=whatsNew"}'><i class='fa fa-question-circle'></i>&nbsp; {lang="whats_new_link"}</a></li>
			<li class='ipsMenu_item'><a href='{url="app=core&module=members&controller=members&do=adminDetails"}' data-ipsDialog data-ipsDialog-url='{url="app=core&module=members&controller=members&do=adminDetails"}' data-ipsDialog-title='{lang="change_details"}' data-ipsDialog-size='narrow'><i class='fa fa-pencil'></i>&nbsp; {lang="change_details"}</a></li>
			{{$languages = \IPS\Lang::roots();}}
			{{if count( $languages ) > 1}}
				<li class='ipsMenu_item ipsMenu_subItems'>
					<a href='#elNavLang_menu' id='elNavLang'><i class='fa fa-globe'></i>&nbsp; {lang='acp_language'}</a>
					<ul id='elNavLang_menu' class='ipsMenu ipsMenu_selectable ipsHide'>
					{{foreach $languages as $id => $lang }}
						<li class='ipsMenu_item{{if \IPS\Member::loggedIn()->acp_language == $id || ( $lang->default && \IPS\Member::loggedIn()->acp_language === 0 )}} ipsMenu_itemChecked{{endif}}'>
							<a href='{url="app=core&module=system&controller=language&id=$id" csrf="true"}'>{{if $lang->get__icon()}}<i class='{$lang->get__icon()}'></i> {{endif}}{$lang->title} {{if $lang->default}}{lang="default"}{{endif}}</a>
						</li>
					{{endforeach}}
					</ul>
				</li>
			{{endif}}
			{{if count( \IPS\Theme::themes() ) > 1}}
				<li class='ipsMenu_item ipsMenu_subItems'>
					<a href='#elNavTheme_menu' id='elNavTheme'><i class='fa fa-leaf'></i>&nbsp; {lang='acp_skin'}</a>
					<ul id='elNavTheme_menu' class='ipsMenu ipsMenu_selectable ipsHide'>
					{{foreach \IPS\Theme::themes() as $id => $set }}
						{{if $set->canAccess()}}
							<li class='ipsMenu_item{{if \IPS\Member::loggedIn()->acp_skin == $id || ($set->is_acp_default && \IPS\Member::loggedIn()->acp_skin === 0 )}} ipsMenu_itemChecked{{endif}}'>
								<a href='{url="app=core&module=system&controller=theme&id=$id" csrf="true"}'>{lang="$set->_title"} {{if $set->is_acp_default}}{lang="default"}{{endif}}</a>
							</li>
						{{endif}}
					{{endforeach}}
					</ul>
				</li>
			{{endif}}
			<li class='ipsMenu_sep'><hr></li>
			<li class='ipsMenu_item'><a href='{url="app=core&module=system&controller=login&do=logout"}'><i class='fa fa-power-off'></i>&nbsp; {lang="sign_out"}</a></li>
		</ul>
		{{if isset( \IPS\Output::i()->sidebar['mobilenav'] )}}{expression="\IPS\Output::i()->sidebar['mobilenav']" raw="true"}{{endif}}
	</body>
</html>