<ips:template parameters="$url, $coverPhoto" />
<div class='ipsPageHead_special ipsCoverPhoto' data-controller='core.global.core.coverPhoto' data-url="{$url->csrf()}" data-coverOffset='{$coverPhoto->offset}'>
	{{$cfObject = $coverPhoto->object;}}
	{{if $coverPhoto->file}}
		<div class='ipsCoverPhoto_container'>
			<img src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
		</div>
	{{elseif ! empty( $cfObject::$coverPhotoDefault )}}
		<div class='ipsCoverPhoto_container' style="background-color: {$coverPhoto->object->coverPhotoBackgroundColor()}">
			<img src='{resource="pattern.png" app="core" location="global"}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
		</div>
	{{endif}}
	{{$id = mt_rand();}}
	{{if $coverPhoto->editable}}
		<a href='#elEditPhoto{$id}_menu' data-hideOnCoverEdit class='ipsCoverPhoto_button ipsPos_right ipsButton ipsButton_verySmall ipsButton_narrow ipsButton_overlaid' data-ipsMenu id='elEditPhoto{$id}' data-role='coverPhotoOptions'>{lang="cover_photo_button"} <i class='fa fa-caret-down'></i></a>
	{{endif}}
	<div class='ipsColumns ipsColumns_collapsePhone' data-hideOnCoverEdit>
		<div class='ipsColumn ipsColumn_fluid'>
			{{if $coverPhoto->editable}}
				<ul class='ipsMenu ipsMenu_auto ipsHide' id='elEditPhoto{$id}_menu'>
					{{if $coverPhoto->file}}
						<li class='ipsMenu_item' data-role='photoEditOption'>
							<a href='{$url->setQueryString( 'do', 'coverPhotoRemove' )->csrf()}' data-action='removeCoverPhoto'>{lang="cover_photo_remove"}</a>
						</li>
						<li class='ipsMenu_item ipsHide' data-role='photoEditOption'>
							<a href='#' data-action='positionCoverPhoto'>{lang="cover_photo_reposition"}</a>
						</li>
					{{endif}}
					<li class='ipsMenu_item'>
						<a href='{$url->setQueryString( 'do', 'coverPhotoUpload' )}' data-ipsDialog data-ipsDialog-title="{lang="cover_photo_add"}">{lang="cover_photo_add"}</a>
					</li>
				</ul>
			{{endif}}
			{$coverPhoto->overlay|raw}
		</div>
	</div>
</div>