<ips:template parameters="$item, $url, $image=NULL" />

<div data-embedInfo-maxSize='500' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, \IPS\Member::loggedIn()->language()->addToStack( 'embed_posted_item', FALSE, array( 'sprintf' => array( $item->author()->name, $item->container()->_title ) ) ), $item->mapped('date'), $url"}
	{{if $image}}
		{{$useImage = $image;}}
	{{elseif $contentImage = $item->contentImages(1)}}
		{{$attachType = key( $contentImage[0] );}}
		{{$useImage = \IPS\File::get( $attachType, $contentImage[0][ $attachType ] );}}
	{{endif}}

	{{if $useImage}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $useImage->url )"}" )'>
				<img src='{$useImage->url}' class='ipsHide' alt=''>
			</a>
		</div>
	{{endif}}
	<div class='ipsPad_double ipsClearfix'>
		<p class='ipsRichEmbed_itemTitle ipsType_reset ipsTruncate ipsTruncate_line ipsType_blendLinks'>
			<a href='{$url}'>{$item->mapped('title')}</a>
		</p>
		{{if $desc = $item->truncated(TRUE)}}
			<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
		{template="embedItemStats" group="embed" app="core" params="$item"}
	</div>
</div>