<ips:template parameters="$image, $name, $size='medium', $classes='', $lang='view_this', $url='', $extension='core_Attachment', $dataParam=''" />

{{if $image}}
	{{$image = ( $image instanceof \IPS\File ) ? (string) $image->url : $image;}}
	{{if $url}}<a {{if $dataParam}}{$dataParam} {{endif}}href='{$url}' title='{lang="$lang" sprintf="$name"}'{{else}}<span{{endif}} style='background-image: url( "{file="$image" extension="$extension"}" )' class='{$classes} ipsThumb ipsThumb_{$size} ipsThumb_bg'>
		<img src='{file="$image" extension="$extension"}' alt=''>
	{{if $url}}</a>{{else}}</span>{{endif}}
{{else}}
	{{if $url}}<a {{if $dataParam}}{$dataParam} {{endif}}href='{$url}' title='{lang="$lang" sprintf="$name"}'{{else}}<span{{endif}} class='{$classes} ipsNoThumb ipsThumb ipsThumb_{$size}'>{{if $url}}</a>{{else}}</span>{{endif}}
{{endif}} 