<ips:template parameters=" " />
{{if \IPS\Member::loggedIn()->member_id }}
	<ul id='elUserNav' class='ipsList_inline cSignedIn ipsClearfix ipsResponsive_showDesktop' data-controller='core.front.core.userbar{{if member.member_id && settings.auto_polling_enabled}},core.front.core.instantNotifications{{endif}}'>
		{{if theme.volpe_userbar_createbutton}}
			{{if !\IPS\Member::loggedIn()->restrict_post and count( \IPS\Member::loggedIn()->createMenu() )}}
				<li id='cCreate'>
					<a href='#elCreateNew_menu' id='elCreateNew' data-ipsTooltip data-ipsMenu title='{lang="create_menu_title"}'>
						<strong><i class='fa fa-plus'></i> &nbsp;{lang="create_menu"}</strong> <i class='fa fa-caret-down'></i>
					</a>
					<div id='elCreateNew_menu' class='ipsMenu ipsMenu_auto ipsHide'>
						<ul>
							{{foreach \IPS\Member::loggedIn()->createMenu() as $k => $url}}
								<li class="ipsMenu_item">
									<a href="{$url['link']}"
									{{if isset( $url['extraData'] )}}
										{{foreach $url['extraData'] as $data => $v}}
											{$data}="{$v}"
										{{endforeach}}
									{{endif}}
									{{if isset($url['title']) AND $url['title']}} 	data-ipsDialog-title='{lang="$url['title']"}'{{endif}}
									{{if isset($url['flashMessage'])}} 	data-ipsdialog-flashmessage="{lang="$url['flashMessage']"}"{{endif}}
									>{lang="$k"}</a>
								</li>
							{{endforeach}}
						</ul>
					</div>
				</li>
				<li class='elUserNav_sep'></li>
			{{endif}}
		{{endif}}
		<li class='cNotifications cUserNav_icon'>
			<a href='{url="app=core&module=system&controller=notifications" seoTemplate="notifications"}' id='elFullNotifications' data-ipsTooltip title='{lang="userbar_notifications" escape="true"}' data-ipsMenu data-ipsMenu-closeOnClick='false'>
				{{foreach explode(',',theme.volpe_userbar_notification) as $key => $icon}}<i class='fa fa-{$icon}'></i>{{endforeach}}<span class='ipsNotificationCount {{if !member.notification_cnt}}ipsHide{{endif}}' data-notificationType='notify' data-currentCount='{member="notification_cnt"}'>{member="notification_cnt"}</span>
			</a>
			<div id='elFullNotifications_menu' class='ipsMenu ipsMenu_wide ipsHide'>
				<div class='ipsMenu_headerBar'>
					<a href="{url="app=core&module=system&controller=notifications&do=options" seoTemplate="notifications_options"}" class="ipsType_light ipsPos_right"><i class="fa fa-cog"></i> {lang="notification_options"}</a>
					<h4 class='ipsType_sectionHead'>{lang="notifications"}</h4>
				</div>
				<div class='ipsMenu_innerContent'>
					<ol class='ipsDataList ipsDataList_readStatus' data-role='notifyList' data-ipsKeyNav data-ipsKeyNav-observe='return' id='elNotifyContent'></ol>
				</div>
				<div class='ipsMenu_footerBar ipsType_center'>
					<a href='{url="app=core&module=system&controller=notifications" seoTemplate="notifications"}'><i class='fa fa-bars'></i> {lang="see_all_notifications"}</a>
				</div>
			</div>
		</li>
		{{if !\IPS\Member::loggedIn()->members_disable_pm and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) )}}
			<li class='cInbox cUserNav_icon'>
				<a href='{url="app=core&module=messaging&controller=messenger" seoTemplate="messaging"}' id='elFullInbox' data-ipsTooltip title='{lang="userbar_messages" escape="true"}' data-ipsMenu data-ipsMenu-closeOnClick='false'>
					{{foreach explode(',',theme.volpe_userbar_messages) as $key => $icon}}<i class='fa fa-{$icon}'></i>{{endforeach}}<span class='ipsNotificationCount {{if !\IPS\Member::loggedIn()->msg_count_new}}ipsHide{{endif}}' data-notificationType='inbox' data-currentCount='{member="msg_count_new"}'>{member="msg_count_new"}</span>
				</a>
				<div id='elFullInbox_menu' class='ipsMenu ipsMenu_wide ipsHide' data-controller='core.front.core.messengerMenu'>
					<div class='ipsMenu_headerBar'>
						<a href='{url="app=core&module=messaging&controller=messenger&do=compose" seoTemplate="messenger_compose"}' data-ipsDialog data-ipsDialog-title='{lang="compose_new"}' data-ipsDialog-remoteSubmit data-ipsDialog-destructOnClose data-ipsDialog-flashMessage="{lang="message_sent"}" id='elMessengerPopup_compose' class='ipsPos_right ipsButton ipsButton_primary ipsButton_verySmall'>{lang="compose_new"}</a>
						<h4 class='ipsType_sectionHead'>{lang="inbox"}</h4>
					</div>
					<div class='ipsMenu_innerContent'><ol class='ipsDataList' data-role='inboxList' data-ipsKeyNav data-ipsKeyNav-observe='return' id='elInboxContent'></ol></div>
					<div class='ipsMenu_footerBar ipsType_center'>
						<a href='{url="app=core&module=messaging&controller=messenger" seoTemplate="messaging"}'><i class='fa fa-bars'></i> {lang="go_to_inbox"}</a>
					</div>
				</div>
			</li>
		{{endif}}
		{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) ) and \IPS\Member::loggedIn()->modPermission('can_view_reports')}}
			<li class='cReports cUserNav_icon'>
				<a href='{url="app=core&module=modcp&controller=modcp&tab=reports" seoTemplate="modcp_reports"}' id='elFullReports' data-ipsTooltip title='{lang="userbar_reports" escape="true"}' data-ipsMenu data-ipsMenu-closeOnClick='false'>
					{{foreach explode(',',theme.volpe_userbar_reported) as $key => $icon}}<i class='fa fa-{$icon}'></i>{{endforeach}}{{if \IPS\Member::loggedIn()->reportCount()}}<span class='ipsNotificationCount' data-notificationType='reports'>{member="reportCount()"}</span>{{endif}}
				</a>
				<div id='elFullReports_menu' class='ipsMenu ipsMenu_wide ipsHide'>
					<div class='ipsMenu_headerBar'><h4 class='ipsType_sectionHead'>{lang="report_center_header"}</h4></div>
					<div class='ipsMenu_innerContent' data-role="reportsList"></div>
					<div class='ipsMenu_footerBar ipsType_center'>
						<a href='{url="app=core&module=modcp&controller=modcp&tab=reports" seoTemplate="modcp_reports"}'><i class='fa fa-bars'></i> {lang="report_center_link"}</a>
					</div>
				</div>
			</li>
		{{endif}}
		<li class='elUserNav_sep'></li>
		<li id='cUserLink'>
			{template="userPhoto" group="global" app="core" params="\IPS\Member::loggedIn(), 'tiny'"}
			<a href='#elUserLink_menu' id='elUserLink' data-ipsMenu>
				{{if theme.volpe_userbar_nickname == "1"}}{{if isset( $_SESSION['logged_in_as_key'] )}}{lang="front_logged_in_as" sprintf="$_SESSION['logged_in_from']['name']"} {{endif}}{member="name"} {{endif}}<i class='fa fa-caret-down'></i>
			</a>
			<ul id='elUserLink_menu' class='ipsMenu ipsMenu_normal ipsHide'>
				<li class='ipsMenu_title'>{lang="menu_content"}</li>
				{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'members', 'front' ) )}}
					<li class='ipsMenu_item' data-menuItem='profile'><a href='{member="url()"}' title='{lang="view_my_profile"}'>{lang="menu_profile"}</a></li>
				{{endif}}
				{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) ) and \IPS\Member::loggedIn()->members_disable_pm AND \IPS\Member::loggedIn()->members_disable_pm != 2}}
					<li class='ipsMenu_item' data-menuItem='messages'><a href='{url="app=core&module=messaging&controller=messenger&do=enableMessenger" seoTemplate="messaging" csrf="true"}' title='{lang="go_to_messenger"}' data-confirm data-confirmMessage='{lang="messenger_disabled_msg"}'>{lang="menu_messages"}</a></li>
				{{endif}}
				{{if \IPS\Member::loggedIn()->group['g_attach_max'] != 0}}
					<li class='ipsMenu_item' data-menuItem='attachments'><a href='{url="app=core&module=system&controller=attachments" seoTemplate="attachments"}'>{lang="my_attachments"}</a></li>
				{{endif}}
				<li class='ipsMenu_title'>{lang="menu_settings_title"}</li>
				{{if \IPS\core\Promote::promoteServices()}}
					<li class='ipsMenu_item' data-menuItem='promote'><a href='{url="app=core&module=promote&controller=promote&do=view" seoTemplate="promote_manage"}'>{lang="promote_manage_link"}</a></li>
				{{endif}}
				<li class='ipsMenu_item' data-menuItem='manageFollowed'><a href='{url="app=core&module=system&controller=followed" seoTemplate="followed_content"}'>{lang="menu_followed_content"}</a></li>
				<li class='ipsMenu_item' id='elAccountSettingsLink' data-menuItem='settings'><a href='{url="app=core&module=system&controller=settings" seoTemplate="settings"}' title='{lang="edit_account_settings"}'>{lang="menu_settings"}</a></li>
				{{if settings.ignore_system_on}}
            	    <li class='ipsMenu_item' data-menuItem='ignoredUsers'><a href='{url="app=core&module=system&controller=ignore" seoTemplate="ignore"}'>{lang="menu_manage_ignore"}</a></li>
            	{{endif}}
				<li class='ipsMenu_sep'><hr></li>
				{{if ( \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) ) AND \IPS\Member::loggedIn()->modPermission() ) or \IPS\Member::loggedIn()->isAdmin()}}
					{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) ) AND \IPS\Member::loggedIn()->modPermission()}}
						<li class='ipsMenu_item' data-menuItem='modcp'><a href='{url="app=core&module=modcp" seoTemplate="modcp"}'>{lang="menu_modcp"}</a></li>
					{{endif}}
					{{if \IPS\Member::loggedIn()->isAdmin() AND !\IPS\Settings::i()->security_remove_acp_link }}
						<li class='ipsMenu_item' data-menuItem='admincp'><a href='{url="" base="admin"}' target='_blank'><i class='fa fa-lock'></i> {lang="menu_admincp"}</a></li>
					{{endif}}
					<li class='ipsMenu_sep'><hr></li>
				{{endif}}
				<li class='ipsMenu_item' data-menuItem='signout'>
					<a href='{url="app=core&module=system&controller=login&do=logout" csrf="true" seoTemplate="logout"}'>
						{{if isset( $_SESSION['logged_in_as_key'] )}}{lang="switch_to_account" sprintf="$_SESSION['logged_in_from']['name']"}{{else}}{lang="sign_out"}{{endif}}
					</a>
				</li>
			</ul>
		</li>
	</ul>
{{else}}
	<ul id='elUserNav' class='ipsList_inline cSignedOut ipsClearfix ipsResponsive_hidePhone ipsResponsive_block'>
		<li id='elSignInLink'>
			{{if \IPS\Settings::i()->logins_over_https AND !\IPS\Request::i()->isSecure()}}
				<a href='{url="app=core&module=system&controller=login" seoTemplate="login" protocol="\IPS\Settings::i()->logins_over_https"}'>{lang="sign_in"}</a>
			{{else}}
				<a href='{url="app=core&module=system&controller=login" seoTemplate="login" protocol="\IPS\Settings::i()->logins_over_https"}' data-ipsMenu-closeOnClick="false" data-ipsMenu id='elUserSignIn'>
					{lang="sign_in"} &nbsp;<i class='fa fa-caret-down'></i>
				</a>
			{{endif}}
			{template="loginPopup" app="core" group="global" params="new \IPS\Login( \IPS\Http\Url::internal( 'app=core&module=system&controller=login', 'front', 'login', NULL, \IPS\Settings::i()->logins_over_https ) )"}
		</li>
		{{if \IPS\Settings::i()->allow_reg}}
			<li>
				<a href='{url="app=core&module=system&controller=register" seoTemplate="register" protocol="\IPS\Settings::i()->logins_over_https"}' {{if \IPS\Settings::i()->quick_register}}data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="sign_up"}'{{endif}} id='elRegisterButton' class='ipsButton ipsButton_normal ipsButton_primary'>
						{lang="sign_up"}
				</a>
			</li>
		{{endif}}
	</ul>
{{endif}}