<ips:template parameters="$newVersion, $features, $cols, $blocks, $info, $bulletins, $warnings" />

<div data-controller='core.admin.dashboard.main{{if $features}},core.admin.dashboard.newFeatures{{endif}}' {{if $features}}data-newFeatures='{$features}'{{endif}}>

	{{if $newVersion}}
		<div id='acpNewVersion' class='cDashboard_bulletin {{if $newVersion['security']}}cDashboard_securityFix{{endif}}'>
			<div class='ipsPad ipsPhotoPanel ipsPhotoPanel_small ipsPhotoPanel_notPhone'>
				
				{{if $newVersion['security']}}
					<i class='fa fa-warning ipsPos_left ipsResponsive_hidePhone'></i>
				{{else}}
					<i class='fa fa-info-circle ipsPos_left ipsResponsive_hidePhone'></i>
				{{endif}}

				<div>
					<h2 class='ipsType_reset'>
						{{if $newVersion['security']}}
							{lang="dashboard_version_info_security" sprintf="$newVersion['version']"}
						{{else}}
							{lang="dashboard_version_info" sprintf="$newVersion['version']"}
						{{endif}}
					</h2>
					
					<p class='ipsType_reset ipsType_normal'>{lang="regular_update" sprintf="$newVersion['released']"}</p>

					<hr class='ipsHr'>

					{{if member.hasAcpRestriction( 'core', 'overview', 'upgrade_manage' ) || $newVersion['updateurl'] || (isset( $newVersion['releasenotes'] ) and $newVersion['releasenotes'])}}
						<ul class='ipsList_inline ipsSpacer_top'>
							{{if member.hasAcpRestriction( 'core', 'overview', 'upgrade_manage' )}}
								<li><a href="{url="app=core&module=system&controller=upgrade&_new=1"}" class='ipsButton ipsButton_veryLight ipsButton_small'>{lang="upgrade_now"}</a></li>
							{{endif}}
							{{if $newVersion['updateurl']}}
								<li><a href='{$newVersion['updateurl']}' target="_blank" class='ipsButton ipsButton_alternate ipsButton_small'>{lang="dashboard_version_moreinfo"}</a></li>
							{{endif}}
							{{if isset( $newVersion['releasenotes'] ) and $newVersion['releasenotes']}}
								<li>{lang="or"}</li>
								<li><a href='#' data-ipsDialog data-ipsDialog-content='#elDashboardNewVersion' data-ipsDialog-fixed data-ipsDialog-title="{lang="whats_new_title" sprintf="$newVersion['version']"}">{lang="see_whats_new"} <i class='fa fa-angle-right'></i></a></li>
							{{endif}}
						</ul>
					{{endif}}
				</div>
			</div>
		</div>
		{{if isset( $newVersion['releasenotes'] ) and $newVersion['releasenotes']}}
			<div id='elDashboardNewVersion' class='ipsHide'>
				<div class='ipsPad ipsType_richText'>
					<div class='ipsType_richText ipsType_normal'>{$newVersion['releasenotes']|raw}</div>
				</div>
			</div>
		{{endif}}
	{{endif}}
	
	{{if count($bulletins)}}
		{{foreach $bulletins as $bulletin}}
			<div class='ipsAreaBackground_light ipsPad ipsPhotoPanel ipsPhotoPanel_small ipsPhotoPanel_notPhone cDashboard_bulletin'>
				<i class='fa fa-info-circle ipsPos_left ipsResponsive_hidePhone'></i>
				<div>
					<h2 class='ipsType_sectionHead'><strong>{$bulletin['title']}</strong></h2>
					<div class='ipsType_normal ipsType_reset'>{$bulletin['description']|raw}</div>
					<br>
					<a href='{$bulletin['link']}' class='ipsButton ipsButton_primary ipsButton_small'>{lang="dashboard_version_moreinfo"} &nbsp;<i class='fa fa-chevron-right'></i></a>
				</div>
			</div>
			<br>
		{{endforeach}}
	{{endif}}

	{{if count($warnings)}}
	<div id='acpWarnings'>
		{{foreach $warnings as $warning}}
		<div class='ipsMessage ipsMessage_warning' {{if isset($warning['key'])}}data-warningKey="{$warning['key']}"{{endif}}>
            {{if isset($warning['key'])}}<a href='#' class='ipsMessage_close ipsPos_right'  data-ipsTooltip title='{lang="close_warning"}'><i class='fa fa-times'></i></a>{{endif}}
			<h4 class='ipsMessage_title'>{$warning['title']}</h4>
			<div class='ipsType_normal ipsType_reset'>{$warning['description']|raw}</div>
		</div>
		<br>
		{{endforeach}}
	</div>
	{{endif}}

	<div class='ipsGrid ipsGrid_collapseTablet'>
		<div class='ipsGrid_span8' data-role="mainerColumn">
			<ol class='ipsList_reset' data-role="mainColumn">
				{{foreach $cols['main'] as $cellKey}}
					{{if array_key_exists( $cellKey, $blocks ) and isset($info[ $cellKey ])}}
						{template="widgetWrapper" group="dashboard" app="core" params="$blocks[ $cellKey ], $info[ $cellKey ], $cols['collapsed']"}
					{{endif}}
				{{endforeach}}
			</ol>
		</div>
		<div class='ipsGrid_span4 acpWidget_sidebar'>
			<ol class='ipsList_reset' data-role="sideColumn">
				{{foreach $cols['side'] as $cellKey}}
					{{if array_key_exists( $cellKey, $blocks ) and isset($info[ $cellKey ])}}
						{template="widgetWrapper" group="dashboard" app="core" params="$blocks[ $cellKey ], $info[ $cellKey ], $cols['collapsed']"}
					{{endif}}
				{{endforeach}}
			</ol>
		</div>
	</div>
</div>