<ips:template parameters="$history" />
<div class='ipsPad'>
	{{if $history === NULL}}
		{lang="promote_history_none"}
	{{else}}
		<div class="ipsColumns ipsColumns_collapsePhone">
		<section class="ipsColumn ipsColumn_fluid">
		<div class="ipsBox ipsPad ipsSpacer_bottom">
			<ol class="ipsStream ipsStream_withTimeline ipsList_reset ipsSpacer_top">
			{{foreach $history as $date => $keys}}
				<li class="ipsStreamItem_time">{datetime="$date"}</li>
				{{foreach $keys as $service => $row}}
					{{foreach $row as $data}}
						{{$promoter = \IPS\core\Promote::getPromoter( $service );}}
						{{$formattedDate = \IPS\DateTime::ts( $data['response_date'] );}}
						<li class="ipsStreamItem ipsStreamItem_contentBlock ipsStreamItem_expanded ipsAreaBackground_reset ipsPad" data-role="activityItem" data-timestamp="{$date}">
							<div class="ipsStreamItem_container ipsClearfix">
								<div class="ipsStreamItem_header">
									<span class="ipsStreamItem_contentType" data-ipsTooltip title="{$service}"><i class="fa fa-{$promoter::$icon}"></i></span>
									<div>
										{lang="promote_history_response_text" sprintf="$promoter->getName( $data['response_service_id'] ), $formattedDate"}
									</div>
								</div>
							</div>
						</li>
					{{endforeach}}
				{{endforeach}}
			{{endforeach}}
			<li class="ipsStreamItem_terminator">&nbsp;</li>
			</ol>
		</div>
	</section>
	{{endif}}
</div>
