<ips:template parameters="$client, $secret, $bruteForce" />
{{if $client->type == 'wordpress'}}
	<p class="ipsType_normal">{lang="oauth_wordpress_blurb"}</p>
	<h2 class="ipsBox_title">{lang="oauth_wordpress_app_settings"}</h2>
	<div class="ipsBox ipsSpacer_bottom">
		<ul class="ipsDataList">
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_application"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					{lang="oauth_wordpress_application_val"}
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_app_name"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					{setting="board_name"}
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_client_id"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>{$client->client_id}</code>
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_client_secret"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					{{if $secret}}
						<code>{$secret}</code><br>
						<span class="ipsType_warning"><i class="fa fa-exclamation-triangle"></i> {lang="oauth_client_secret_desc"}</span>
					{{else}}
						<span class="ipsType_light">{lang="hidden"}</span>
						{{if member.hasAcpRestriction( 'core', 'applications', 'oauth_secrets' )}}
							<br>
							<a href="{url="app=core&module=applications&controller=api&tab=oauth&do=view&client_id={$client->client_id}&newSecret=1"}" data-confirm data-confirmSubMessage="{lang="oauth_regenerate_warning"}">{lang="oauth_regenerate_secret"}</a>
						{{endif}}
					{{endif}}
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_scope"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>email</code>
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_authorize_uri"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>{url="oauth/authorize/" base="interface" protocol="\IPS\Http\Url::PROTOCOL_HTTPS"}</code>
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_token_uri"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>{url="oauth/token/" base="interface" protocol="\IPS\Http\Url::PROTOCOL_HTTPS"}</code>
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_user_uri"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					{{if settings.use_friendly_urls and settings.htaccess_mod_rewrite}}
						<code>{expression="rtrim( \IPS\Settings::i()->base_url, '/' )"}/api/core/me</code>
					{{else}}
						<code>{expression="rtrim( \IPS\Settings::i()->base_url, '/' )"}/api/index.php?/core/me</code>
					{{endif}}
				</span>
			</li>
		</ul>
	</div>
	<h2 class="ipsBox_title">{lang="oauth_wordpress_attribute_mapping"}</h2>
	<div class="ipsBox ipsSpacer_bottom">
		<ul class="ipsDataList">
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_map_email"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>email</code>
				</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_wordpress_map_name"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>name</code>
				</span>
			</li>
		</ul>
	</div>
{{else}}
	<h2 class="ipsBox_title">{lang="oauth_client_credentials"}</h2>
	<div class="ipsBox ipsSpacer_bottom">
		<ul class="ipsDataList">
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size6">
					<strong>{lang="oauth_client_id"}</strong>
				</span>
				<span class="ipsDataItem_generic">
					<code>{$client->client_id}</code>
				</span>
			</li>
			{{if $client->client_secret}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size6">
						<strong>{lang="oauth_client_secret"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{{if $secret}}
							<code>{$secret}</code><br>
							<span class="ipsType_warning"><i class="fa fa-exclamation-triangle"></i> {lang="oauth_client_secret_desc"}</span>
						{{else}}
							<span class="ipsType_light">{lang="hidden"}</span>
							{{if member.hasAcpRestriction( 'core', 'applications', 'oauth_secrets' )}}
								<br>
								<a href="{url="app=core&module=applications&controller=api&tab=oauth&do=view&client_id={$client->client_id}&newSecret=1"}" data-confirm data-confirmSubMessage="{lang="oauth_regenerate_warning"}">{lang="oauth_regenerate_secret"}</a>
							{{endif}}
						{{endif}}
					</span>
				</li>
			{{endif}}
		</ul>
	</div>
	{{if $client->type != 'invision'}}
		<div class="ipsSpacer_bottom">
			<h2 class="ipsBox_title">{lang="oauth_endpoint_details"}</h2>
			<div class="ipsBox">
				<ul class="ipsDataList">
					{{$grants = explode( ',', $client->grant_types );}}
					{{if in_array( 'authorization_code', $grants ) or in_array( 'token', $grants )}}
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size6">
								<strong>{lang="oauth_authorize_uri"}</strong>
							</span>
							<span class="ipsDataItem_generic">
								<code>{url="oauth/authorize/" base="interface" protocol="\IPS\Http\Url::PROTOCOL_HTTPS"}</code><br>
								{{if in_array( 'authorization_code', $grants ) and in_array( 'token', $grants )}}
									<span class="ipsType_desc">{lang="oauth_authorize_uri_desc_3"}</span>
								{{elseif in_array( 'authorization_code', $grants )}}
									<span class="ipsType_desc">{lang="oauth_authorize_uri_desc_1"}</span>
								{{else}}
									<span class="ipsType_desc">{lang="oauth_authorize_uri_desc_2"}</span>
								{{endif}}
							</span>
						</li>
					{{endif}}
					{{if in_array( 'authorization_code', $grants ) or in_array( 'client_credentials', $grants ) or in_array( 'password', $grants )}}
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size6">
								<strong>{lang="oauth_token_uri"}</strong>
							</span>
							<span class="ipsDataItem_generic">
								<code>{url="oauth/token/" base="interface" protocol="\IPS\Http\Url::PROTOCOL_HTTPS"}</code><br>
								<span class="ipsType_desc">{lang="oauth_token_uri_desc"}</span>
							</span>
						</li>
					{{endif}}
				</ul>
			</div>
		</div>
	{{endif}}
{{endif}}

{{if $bruteForce}}
	<div class="ipsSpacer_bottom">
		<h2 class="ipsBox_title">{lang="oauth_brute_force"}</h2>
		<div class="ipsType_light">{lang="oauth_brute_force_desc"}</div>
		{$bruteForce|raw}
	</div>
{{endif}}