<ips:template parameters="$endpoints, $name, $value, $type=NULL" />

<li class='ipsFieldRow ipsPad_half ipsClearfix'>
	<div class='ipsFieldRow_title'>
		{lang="api_permissions_endpoint"}
	</div>
	<div class='ipsFieldRow_content'>
		<p class='ipsType_reset ipsSpacer_bottom'>
			{lang="api_permissions_endpoint_desc"}
		</p>

		{template="permissionsFieldHtml" group="api" params="$endpoints, $name, $value, $type"}
	</div>
</li>
