<ips:template parameters="$announcements" />

<div class='ipsBox ipsSpacer_bottom' id="cAnnouncementSidebar">
	<span class="cAnnouncementIcon"><i class='fa fa-bullhorn fa-3x fa-fw'></i></span>
	<h3>{lang="announcements"}</h3>
	<ul>
	{{foreach $announcements as $announcement}}
		<li class="cAnnouncementSidebar ipsMessage ipsMessage_{$announcement->color}"><a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{$announcement->title}</a></li>
	{{endforeach}}
	</ul>
</div>