<ips:template parameters="$app, $area, $id, $count" />
{{if member.member_id}}
	{{if member.following( $app, $area, $id )}}
		<div class="ipsFollow ipsButton ipsButton_primary ipsButton_verySmall" data-role="followButton" data-following="true">
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="following_this_content"}" data-ipsTooltip class="ipsType_blendLinks ipsType_noUnderline" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-check'></i> {lang="following_this"} <i class='fa fa-caret-down'></i></a>
			<a class='ipsCommentCount' href='{url="app=core&module=system&controller=notifications&do=followers&follow_app={$app}&follow_area={$area}&follow_id={$id}"}' title='{lang="followers_tooltip"}' data-ipsTooltip data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="who_follows_this"}'>{$count}</a>
		</div>
	{{else}}	
		<div class="ipsFollow ipsButton ipsButton_link ipsButton_verySmall" data-role="followButton" data-following="false">
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="follow_this_content"}" data-ipsTooltip class="ipsType_blendLinks ipsType_noUnderline" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick>{lang="follow"}</a>
			{{if $count > 0}}
				<a class='ipsCommentCount' href='{url="app=core&module=system&controller=notifications&do=followers&follow_app={$app}&follow_area={$area}&follow_id={$id}"}' title='{lang="followers_tooltip"}' data-ipsTooltip data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="who_follows_this"}'>{$count}</a>
			{{else}}
				<span class='ipsCommentCount'>{$count}</span>
			{{endif}}
		</div>
	{{endif}}
{{else}}
	<div class="ipsFollow ipsPos_middle ipsButton ipsButton_link ipsButton_verySmall {{if $count == 0}}ipsButton_disabled{{endif}}" data-role="followButton">
		{{if $count > 0}}
			<a href='{url="app=core&module=system&controller=notifications&do=followers&follow_app={$app}&follow_area={$area}&follow_id={$id}"}' title='{lang="followers_tooltip"}' class='ipsType_blendLinks ipsType_noUnderline' data-ipsTooltip data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="who_follows_this"}'>{lang="followers"}</a>
			<a class='ipsCommentCount' href='{url="app=core&module=system&controller=notifications&do=followers&follow_app={$app}&follow_area={$area}&follow_id={$id}"}' title='{lang="followers_tooltip"}' data-ipsTooltip data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="who_follows_this"}'>{$count}</a>
		{{else}}
			<span>{lang="followers"}</span>
			<span class='ipsCommentCount'>{$count}</span>
		{{endif}}
	</div>
{{endif}}