<ips:template parameters="$preview=FALSE" />
{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}
<nav class="ta_navBar" {{if theme.dummy}}data-controller='core.front.core.navBar' class='{{if !count( \IPS\core\FrontNavigation::i()->subBars( $preview ) )}}ipsNavBar_noSubBars{{endif}}'{{endif}}>
	<div class='ta_navContainer'>
		<div class='ipsNavBar_primary ta_navWrapper{{if theme.dummy}}{{if !count( \IPS\core\FrontNavigation::i()->subBars( $preview ) )}}ipsNavBar_noSubBars{{endif}}{{endif}} ipsClearfix'>
			<ul data-role="primaryNavBar" class='ta_nav'>
				{template="navBarItems" app="core" group="global" location="front" params="\IPS\core\FrontNavigation::i()->roots( $preview ), \IPS\core\FrontNavigation::i()->subBars( $preview ), 0, $preview"}
              	{{if theme.dummy}}<li class='ipsHide' id='elNavigationMore' data-role='navMore'>
					<a href='#' data-ipsMenu data-ipsMenu-appendTo='#elNavigationMore' id='elNavigationMore_dropdown'>{lang="more"}</a>
					<ul class='ipsNavBar_secondary ipsHide' data-role='secondaryNavBar'>
						<li class='ipsHide' id='elNavigationMore_more' data-role='navMore'>
							<a href='#' data-ipsMenu data-ipsMenu-appendTo='#elNavigationMore_more' id='elNavigationMore_more_dropdown'>{lang="more"} <i class='fa fa-caret-down'></i></a>
							<ul class='ipsHide ipsMenu ipsMenu_auto' id='elNavigationMore_more_dropdown_menu' data-role='moreDropdown'></ul>
						</li>
					</ul>
				</li>{{endif}}
			</ul>

          
			{{if !$preview and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'search' ) ) AND !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}
              	<div class='ta_Search'>
					<button type="button" class="ta_searchButton">
						<svg viewBox="0 0 32 32" preserveAspectRatio="xMidYMin">
							<path d="M12.98,0C5.81,0,0,5.81,0,12.98c0,7.17,5.81,12.98,12.98,12.98c7.17,0,12.98-5.81,12.98-12.98C25.97,5.81,20.15,0,12.98,0z M12.98,23.06c-5.56,0-10.07-4.51-10.07-10.07c0-5.56,4.51-10.07,10.07-10.07c5.56,0,10.07,4.51,10.07,10.07 C23.06,18.55,18.55,23.06,12.98,23.06z"></path>
							<path d="M18.08,18.49c0,1.27-2.22,2.3-4.96,2.3s-4.96-1.03-4.96-2.3c0-1.27,2.22-1.64,4.96-1.64S18.08,17.21,18.08,18.49z"></path>
							<path d="M31.25,31.25L31.25,31.25c-1,1-2.64,1-3.65,0l-7.87-7.87c-1-1,0-1.64,1-2.65l0,0c1-1,1.64-2,2.65-1l7.87,7.87 C32.25,28.6,32.25,30.25,31.25,31.25z"></path>
						</svg>
					</button>
                  
				<div id='elSearch' class='ipsPos_right' data-controller='core.front.core.quickSearch' data-default="{expression="\IPS\Output::i()->defaultSearchOption[0]"}">
					<form accept-charset='utf-8' action='{url="app=core&module=search&controller=search" seoTemplate="search"}' method='post'>
						<a href='#' id='elSearchFilter' data-ipsMenu data-ipsMenu-selectable='radio' data-ipsMenu-appendTo='#elSearch' class="ipsHide">
							<span data-role='searchingIn'>
								{{if count( output.contextualSearchOptions )}}
									{{foreach output.contextualSearchOptions as $name => $data}}
										{$name}
										{{$defaultSearchType = $data['type'];}}
										{{foreach $data as $k => $v}}
											<input name="{$k}" value="{$v}" data-role="searchFilter" type="hidden">
										{{endforeach}}
										{{break;}}
									{{endforeach}}
								{{else}}
									{{$defaultSearchType = \IPS\Output::i()->defaultSearchOption[0];}}
									{expression="\IPS\Member::loggedIn()->language()->addToStack( \IPS\Output::i()->defaultSearchOption[1] )"}
								{{endif}}
							</span>
							<i class='fa fa-caret-down'></i>
						</a>
						<input type="hidden" name="type" value="{$defaultSearchType}" data-role="searchFilter">
						<ul id='elSearchFilter_menu' class='ipsMenu ipsMenu_selectable ipsMenu_narrow ipsHide'>
							<li class='ipsMenu_item {{if output.defaultSearchOption[0] == 'all' AND !count(output.contextualSearchOptions)}}ipsMenu_itemChecked{{endif}}' data-ipsMenuValue='all'>
								<a href='{url="app=core&module=search&controller=search" csrf="1"}' title='{lang="search_everything"}'>{lang="search_everything"}</a>
							</li>
							<li class='ipsMenu_sep'><hr></li>
							{{if count( output.contextualSearchOptions )}}
								{{$setDefault = FALSE;}}
								{{foreach output.contextualSearchOptions as $name => $data}}
									<li class='ipsMenu_item {{if $setDefault === FALSE}}ipsMenu_itemChecked{{$setDefault = TRUE;}}{{endif}}' data-ipsMenuValue='{expression="json_encode( $data )"}' data-options='{expression="json_encode( $data )"}'>
										<a href='#'>{$name}</a>
									</li>
								{{endforeach}}
								<li class='ipsMenu_sep'><hr></li>
							{{endif}}
							<li data-role='globalSearchMenuOptions'></li>
							<li class='ipsMenu_item ipsMenu_itemNonSelect'>
								<a href='{url="app=core&module=search&controller=search" seoTemplate="search"}' accesskey='4'><i class='fa fa-cog'></i> {lang="advanced_search"}</a>
							</li>
						</ul>
						<input type='search' id='elSearchField' placeholder='{lang="search_placeholder"}' name='q'>
						<button type='submit'>
							<svg viewBox="0 0 32 32" preserveAspectRatio="xMidYMin">
								<path d="M12.98,0C5.81,0,0,5.81,0,12.98c0,7.17,5.81,12.98,12.98,12.98c7.17,0,12.98-5.81,12.98-12.98C25.97,5.81,20.15,0,12.98,0z M12.98,23.06c-5.56,0-10.07-4.51-10.07-10.07c0-5.56,4.51-10.07,10.07-10.07c5.56,0,10.07,4.51,10.07,10.07 C23.06,18.55,18.55,23.06,12.98,23.06z"></path>
								<path d="M18.08,18.49c0,1.27-2.22,2.3-4.96,2.3s-4.96-1.03-4.96-2.3c0-1.27,2.22-1.64,4.96-1.64S18.08,17.21,18.08,18.49z"></path>
								<path d="M31.25,31.25L31.25,31.25c-1,1-2.64,1-3.65,0l-7.87-7.87c-1-1,0-1.64,1-2.65l0,0c1-1,1.64-2,2.65-1l7.87,7.87 C32.25,28.6,32.25,30.25,31.25,31.25z"></path>
							</svg>
                      	</button>
					</form>
				</div>
                  
				</div>
              {{endif}}                

		</div>
	</div>
</nav>
{{elseif member.group['g_view_board']}}
<nav class="ta_navBar ta_Minimal">
	<div class='ta_navContainer'>
		<div class='ipsNavBar_primary {{if theme.dummy}}ipsNavBar_noSubBars{{endif}} ipsClearfix'>
			<a id='elBackHome' href='{setting="base_url"}' title='{lang="go_community_home"}'><i class='fa fa-angle-left'></i> {lang="community_home"}</a>
		</div>
	</div>
</nav>
{{endif}}
