<ips:template parameters="$content" />
{{if !\IPS\Content\Reaction::isLikeMode()}}
	{{$reactions = \IPS\Content\Reaction::roots();}}
	<ul class='ipsReact_reactions'>
	{{foreach $content->reactBlurb() AS $key => $count}}
		{{if isset( $reactions[ $key ] )}}
			{{$reaction = $reactions[ $key ];}}
			<li class='ipsReact_reactCount'>
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					<a href='{$content->url('showReactions')->setQueryString( 'reaction', $reaction->id )}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="see_who_reacted"}' data-ipsTooltip title="{lang="see_who_reacted_x" sprintf="\IPS\Member::loggedIn()->language()->addToStack( 'reaction_title_' . $reaction->id )" escape="true"}">
				{{else}}
					<span data-ipsTooltip title="{lang="reaction_title_{$reaction->id}" escape="true"}">
				{{endif}}
						<span>
							<img src='{file="$reaction->_icon" extension="core_Reaction"}' alt="{lang="reaction_title_{$reaction->id}" escape="true"}">
						</span>
						<span>
							{$count}
						</span>
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					</a>
				{{else}}
					</span>
				{{endif}}
			</li>
		{{endif}}
	{{endforeach}}
	</ul>
{{else}}
	{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
	<span class='ipsType_blendLinks'>
		{$content->whoReacted()}
	</span>
	{{endif}}
{{endif}}
<div class='ipsReact_overview ipsType_blendLinks'>
	{{if !\IPS\Content\Reaction::isLikeMode() && \IPS\Member::loggedIn()->group['gbw_view_reps']}}
		{$content->whoReacted()}
	{{endif}}
	{{if \IPS\Content\Reaction::isLikeMode() and \IPS\Member::loggedIn()->modPermission('can_remove_reactions')}}
		<a href='{$content->url('showReactions')}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="edit_who_reacted"}' data-ipsTooltip title='{lang="edit_who_reacted"}'>&nbsp;<i class="fa fa-pencil"></i></a>
	{{endif}}
</div>